### Libs

In [7]:
import glob
import json
import os

import kennard_stone as ks
import polars as pl
from dotenv import load_dotenv
from huggingface_hub import HfApi, hf_hub_download
from sklearn.preprocessing import StandardScaler

load_dotenv()

True

### Downloading Dataset

In [2]:
HF_TOKEN = os.getenv("HF_READ_TOKEN")
REPO_ID = "luminary-shift/Pump"
METADATA_DIR = "./pump_metadata"

In [3]:
api = HfApi(token=HF_TOKEN)

# Avoid re-downloading, load from local file
if not os.path.exists("shift_pump_files.txt"):
    # Download from HF
    all_files = api.list_repo_files(repo_id=REPO_ID, repo_type="dataset")
    with open("shift_pump_files.txt", "w") as f:
        f.writelines(f"{file}\n" for file in all_files)
else:
    with open("shift_pump_files.txt", "r") as f:
        all_files = f.read().splitlines()
params_json_files = [f for f in all_files if f.endswith("params.json")]

In [4]:
params_json_files

['sample_000001/params.json',
 'sample_000002/params.json',
 'sample_000003/params.json',
 'sample_000004/params.json',
 'sample_000005/params.json',
 'sample_000006/params.json',
 'sample_000007/params.json',
 'sample_000008/params.json',
 'sample_000009/params.json',
 'sample_000010/params.json',
 'sample_000011/params.json',
 'sample_000012/params.json',
 'sample_000013/params.json',
 'sample_000014/params.json',
 'sample_000015/params.json',
 'sample_000016/params.json',
 'sample_000017/params.json',
 'sample_000018/params.json',
 'sample_000019/params.json',
 'sample_000020/params.json',
 'sample_000021/params.json',
 'sample_000022/params.json',
 'sample_000023/params.json',
 'sample_000024/params.json',
 'sample_000025/params.json',
 'sample_000026/params.json',
 'sample_000027/params.json',
 'sample_000028/params.json',
 'sample_000029/params.json',
 'sample_000030/params.json',
 'sample_000031/params.json',
 'sample_000032/params.json',
 'sample_000033/params.json',
 'sample_000034/params.json',
 'sample_000035/params.json',
 'sample_000036/params.json',
 'sample_000037/params.json',
 'sample_000038/params.json',
 'sample_000039/params.json',
 'sample_000040/params.json',
 'sample_000041/params.json',
 'sample_000042/params.json',
 'sample_000043/params.json',
 'sample_000044/params.json',
 'sample_000045/params.json',
 'sample_000046/params.json',
 'sample_000047/params.json',
 'sample_000048/params.json',
 'sample_000049/params.json',
 'sample_000050/params.json',
 'sample_000051/params.json',
 'sample_000052/params.json',
 'sample_000053/params.json',
 'sample_000054/params.json',
 'sample_000055/params.json',
 'sample_000056/params.json',
 'sample_000057/params.json',
 'sample_000058/params.json',
 'sample_000059/params.json',
 'sample_000060/params.json',
 'sample_000061/params.json',
 'sample_000062/params.json',
 'sample_000063/params.json',
 'sample_000064/params.json',
 'sample_000065/params.json',
 'sample_000066/params.json',
 'sample_000067/params.json',
 'sample_000068/params.json',
 'sample_000069/params.json',
 'sample_000070/params.json',
 'sample_000071/params.json',
 'sample_000072/params.json',
 'sample_000073/params.json',
 'sample_000074/params.json',
 'sample_000075/params.json',
 'sample_000076/params.json',
 'sample_000077/params.json',
 'sample_000078/params.json',
 'sample_000079/params.json',
 'sample_000080/params.json',
 'sample_000081/params.json',
 'sample_000082/params.json',
 'sample_000083/params.json',
 'sample_000084/params.json',
 'sample_000085/params.json',
 'sample_000086/params.json',
 'sample_000087/params.json',
 'sample_000088/params.json',
 'sample_000089/params.json',
 'sample_000090/params.json',
 'sample_000091/params.json',
 'sample_000092/params.json',
 'sample_000093/params.json',
 'sample_000094/params.json',
 'sample_000095/params.json',
 'sample_000096/params.json',
 'sample_000097/params.json',
 'sample_000098/params.json',
 'sample_000099/params.json',
 'sample_000100/params.json',
 'sample_000101/params.json',
 'sample_000102/params.json',
 'sample_000103/params.json',
 'sample_000104/params.json',
 'sample_000105/params.json',
 'sample_000106/params.json',
 'sample_000107/params.json',
 'sample_000108/params.json',
 'sample_000109/params.json',
 'sample_000110/params.json',
 'sample_000111/params.json',
 'sample_000112/params.json',
 'sample_000113/params.json',
 'sample_000114/params.json',
 'sample_000115/params.json',
 'sample_000116/params.json',
 'sample_000117/params.json',
 'sample_000118/params.json',
 'sample_000119/params.json',
 'sample_000120/params.json',
 'sample_000121/params.json',
 'sample_000122/params.json',
 'sample_000123/params.json',
 'sample_000124/params.json',
 'sample_000125/params.json',
 'sample_000126/params.json',
 'sample_000127/params.json',
 'sample_000128/params.json',
 'sample_000129/params.json',
 'sample_000130/params.json',
 'sample_000131/params.json',
 'sample_000132/params.json',
 'sample_000133/params.json',
 'sample_000134/params.json',
 'sample_000135/params.json',
 'sample_000136/params.json',
 'sample_000137/params.json',
 'sample_000138/params.json',
 'sample_000139/params.json',
 'sample_000140/params.json',
 'sample_000141/params.json',
 'sample_000142/params.json',
 'sample_000143/params.json',
 'sample_000144/params.json',
 'sample_000145/params.json',
 'sample_000146/params.json',
 'sample_000147/params.json',
 'sample_000148/params.json',
 'sample_000149/params.json',
 'sample_000150/params.json',
 'sample_000151/params.json',
 'sample_000152/params.json',
 'sample_000153/params.json',
 'sample_000154/params.json',
 'sample_000155/params.json',
 'sample_000156/params.json',
 'sample_000157/params.json',
 'sample_000158/params.json',
 'sample_000159/params.json',
 'sample_000160/params.json',
 'sample_000161/params.json',
 'sample_000162/params.json',
 'sample_000163/params.json',
 'sample_000164/params.json',
 'sample_000165/params.json',
 'sample_000166/params.json',
 'sample_000167/params.json',
 'sample_000168/params.json',
 'sample_000169/params.json',
 'sample_000170/params.json',
 'sample_000171/params.json',
 'sample_000172/params.json',
 'sample_000173/params.json',
 'sample_000174/params.json',
 'sample_000175/params.json',
 'sample_000176/params.json',
 'sample_000177/params.json',
 'sample_000178/params.json',
 'sample_000179/params.json',
 'sample_000180/params.json',
 'sample_000181/params.json',
 'sample_000182/params.json',
 'sample_000183/params.json',
 'sample_000184/params.json',
 'sample_000185/params.json',
 'sample_000186/params.json',
 'sample_000187/params.json',
 'sample_000188/params.json',
 'sample_000189/params.json',
 'sample_000190/params.json',
 'sample_000191/params.json',
 'sample_000192/params.json',
 'sample_000193/params.json',
 'sample_000194/params.json',
 'sample_000195/params.json',
 'sample_000196/params.json',
 'sample_000197/params.json',
 'sample_000198/params.json',
 'sample_000199/params.json',
 'sample_000200/params.json',
 'sample_000201/params.json',
 'sample_000202/params.json',
 'sample_000203/params.json',
 'sample_000204/params.json',
 'sample_000205/params.json',
 'sample_000206/params.json',
 'sample_000207/params.json',
 'sample_000208/params.json',
 'sample_000209/params.json',
 'sample_000210/params.json',
 'sample_000211/params.json',
 'sample_000212/params.json',
 'sample_000213/params.json',
 'sample_000214/params.json',
 'sample_000215/params.json',
 'sample_000216/params.json',
 'sample_000217/params.json',
 'sample_000218/params.json',
 'sample_000219/params.json',
 'sample_000220/params.json',
 'sample_000221/params.json',
 'sample_000222/params.json',
 'sample_000223/params.json',
 'sample_000224/params.json',
 'sample_000225/params.json',
 'sample_000226/params.json',
 'sample_000227/params.json',
 'sample_000228/params.json',
 'sample_000229/params.json',
 'sample_000230/params.json',
 'sample_000231/params.json',
 'sample_000232/params.json',
 'sample_000233/params.json',
 'sample_000234/params.json',
 'sample_000235/params.json',
 'sample_000236/params.json',
 'sample_000237/params.json',
 'sample_000238/params.json',
 'sample_000239/params.json',
 'sample_000240/params.json',
 'sample_000241/params.json',
 'sample_000242/params.json',
 'sample_000243/params.json',
 'sample_000244/params.json',
 'sample_000245/params.json',
 'sample_000246/params.json',
 'sample_000247/params.json',
 'sample_000248/params.json',
 'sample_000249/params.json',
 'sample_000250/params.json',
 'sample_000251/params.json',
 'sample_000252/params.json',
 'sample_000253/params.json',
 'sample_000254/params.json',
 'sample_000255/params.json',
 'sample_000256/params.json',
 'sample_000257/params.json',
 'sample_000258/params.json',
 'sample_000259/params.json',
 'sample_000260/params.json',
 'sample_000261/params.json',
 'sample_000262/params.json',
 'sample_000263/params.json',
 'sample_000264/params.json',
 'sample_000265/params.json',
 'sample_000266/params.json',
 'sample_000267/params.json',
 'sample_000268/params.json',
 'sample_000269/params.json',
 'sample_000270/params.json',
 'sample_000271/params.json',
 'sample_000272/params.json',
 'sample_000273/params.json',
 'sample_000274/params.json',
 'sample_000275/params.json',
 'sample_000276/params.json',
 'sample_000277/params.json',
 'sample_000278/params.json',
 'sample_000279/params.json',
 'sample_000280/params.json',
 'sample_000281/params.json',
 'sample_000282/params.json',
 'sample_000283/params.json',
 'sample_000284/params.json',
 'sample_000285/params.json',
 'sample_000286/params.json',
 'sample_000287/params.json',
 'sample_000288/params.json',
 'sample_000289/params.json',
 'sample_000290/params.json',
 'sample_000291/params.json',
 'sample_000292/params.json',
 'sample_000293/params.json',
 'sample_000294/params.json',
 'sample_000295/params.json',
 'sample_000296/params.json',
 'sample_000297/params.json',
 'sample_000298/params.json',
 'sample_000299/params.json',
 'sample_000300/params.json',
 'sample_000301/params.json',
 'sample_000302/params.json',
 'sample_000303/params.json',
 'sample_000304/params.json',
 'sample_000305/params.json',
 'sample_000306/params.json',
 'sample_000307/params.json',
 'sample_000308/params.json',
 'sample_000309/params.json',
 'sample_000310/params.json',
 'sample_000311/params.json',
 'sample_000312/params.json',
 'sample_000313/params.json',
 'sample_000314/params.json',
 'sample_000315/params.json',
 'sample_000316/params.json',
 'sample_000317/params.json',
 'sample_000318/params.json',
 'sample_000319/params.json',
 'sample_000320/params.json',
 'sample_000321/params.json',
 'sample_000322/params.json',
 'sample_000323/params.json',
 'sample_000324/params.json',
 'sample_000325/params.json',
 'sample_000326/params.json',
 'sample_000327/params.json',
 'sample_000328/params.json',
 'sample_000329/params.json',
 'sample_000330/params.json',
 'sample_000331/params.json',
 'sample_000332/params.json',
 'sample_000333/params.json',
 'sample_000334/params.json',
 'sample_000335/params.json',
 'sample_000336/params.json',
 'sample_000337/params.json',
 'sample_000338/params.json',
 'sample_000339/params.json',
 'sample_000340/params.json',
 'sample_000341/params.json',
 'sample_000342/params.json',
 'sample_000343/params.json',
 'sample_000344/params.json',
 'sample_000345/params.json',
 'sample_000346/params.json',
 'sample_000347/params.json',
 'sample_000348/params.json',
 'sample_000349/params.json',
 'sample_000350/params.json',
 'sample_000351/params.json',
 'sample_000352/params.json',
 'sample_000353/params.json',
 'sample_000354/params.json',
 'sample_000355/params.json',
 'sample_000356/params.json',
 'sample_000357/params.json',
 'sample_000358/params.json',
 'sample_000359/params.json',
 'sample_000360/params.json',
 'sample_000361/params.json',
 'sample_000362/params.json',
 'sample_000363/params.json',
 'sample_000364/params.json',
 'sample_000365/params.json',
 'sample_000366/params.json',
 'sample_000367/params.json',
 'sample_000368/params.json',
 'sample_000369/params.json',
 'sample_000370/params.json',
 'sample_000371/params.json',
 'sample_000372/params.json',
 'sample_000373/params.json',
 'sample_000374/params.json',
 'sample_000375/params.json',
 'sample_000376/params.json',
 'sample_000377/params.json',
 'sample_000378/params.json',
 'sample_000379/params.json',
 'sample_000380/params.json',
 'sample_000381/params.json',
 'sample_000382/params.json',
 'sample_000383/params.json',
 'sample_000384/params.json',
 'sample_000385/params.json',
 'sample_000386/params.json',
 'sample_000387/params.json',
 'sample_000388/params.json',
 'sample_000389/params.json',
 'sample_000390/params.json',
 'sample_000391/params.json',
 'sample_000392/params.json',
 'sample_000393/params.json',
 'sample_000394/params.json',
 'sample_000395/params.json',
 'sample_000396/params.json',
 'sample_000397/params.json',
 'sample_000398/params.json',
 'sample_000399/params.json',
 'sample_000400/params.json',
 'sample_000401/params.json',
 'sample_000402/params.json',
 'sample_000403/params.json',
 'sample_000404/params.json',
 'sample_000405/params.json',
 'sample_000406/params.json',
 'sample_000407/params.json',
 'sample_000408/params.json',
 'sample_000409/params.json',
 'sample_000410/params.json',
 'sample_000411/params.json',
 'sample_000412/params.json',
 'sample_000413/params.json',
 'sample_000414/params.json',
 'sample_000415/params.json',
 'sample_000416/params.json',
 'sample_000417/params.json',
 'sample_000418/params.json',
 'sample_000419/params.json',
 'sample_000420/params.json',
 'sample_000421/params.json',
 'sample_000422/params.json',
 'sample_000423/params.json',
 'sample_000424/params.json',
 'sample_000425/params.json',
 'sample_000426/params.json',
 'sample_000427/params.json',
 'sample_000428/params.json',
 'sample_000429/params.json',
 'sample_000430/params.json',
 'sample_000431/params.json',
 'sample_000432/params.json',
 'sample_000433/params.json',
 'sample_000434/params.json',
 'sample_000435/params.json',
 'sample_000436/params.json',
 'sample_000437/params.json',
 'sample_000438/params.json',
 'sample_000439/params.json',
 'sample_000440/params.json',
 'sample_000441/params.json',
 'sample_000442/params.json',
 'sample_000443/params.json',
 'sample_000444/params.json',
 'sample_000445/params.json',
 'sample_000446/params.json',
 'sample_000447/params.json',
 'sample_000448/params.json',
 'sample_000449/params.json',
 'sample_000450/params.json',
 'sample_000451/params.json',
 'sample_000452/params.json',
 'sample_000453/params.json',
 'sample_000454/params.json',
 'sample_000455/params.json',
 'sample_000456/params.json',
 'sample_000457/params.json',
 'sample_000458/params.json',
 'sample_000459/params.json',
 'sample_000460/params.json',
 'sample_000461/params.json',
 'sample_000462/params.json',
 'sample_000463/params.json',
 'sample_000464/params.json',
 'sample_000465/params.json',
 'sample_000466/params.json',
 'sample_000467/params.json',
 'sample_000468/params.json',
 'sample_000469/params.json',
 'sample_000470/params.json',
 'sample_000471/params.json',
 'sample_000472/params.json',
 'sample_000473/params.json',
 'sample_000474/params.json',
 'sample_000475/params.json',
 'sample_000476/params.json',
 'sample_000477/params.json',
 'sample_000478/params.json',
 'sample_000479/params.json',
 'sample_000480/params.json',
 'sample_000481/params.json',
 'sample_000482/params.json',
 'sample_000483/params.json',
 'sample_000484/params.json',
 'sample_000485/params.json',
 'sample_000486/params.json',
 'sample_000487/params.json',
 'sample_000488/params.json',
 'sample_000489/params.json',
 'sample_000490/params.json',
 'sample_000491/params.json',
 'sample_000492/params.json',
 'sample_000493/params.json',
 'sample_000494/params.json',
 'sample_000495/params.json',
 'sample_000496/params.json',
 'sample_000497/params.json',
 'sample_000498/params.json',
 'sample_000499/params.json',
 'sample_000500/params.json',
 'sample_000501/params.json',
 'sample_000502/params.json',
 'sample_000503/params.json',
 'sample_000504/params.json',
 'sample_000505/params.json',
 'sample_000506/params.json',
 'sample_000507/params.json',
 'sample_000508/params.json',
 'sample_000509/params.json',
 'sample_000510/params.json',
 'sample_000511/params.json',
 'sample_000512/params.json',
 'sample_000513/params.json',
 'sample_000514/params.json',
 'sample_000515/params.json',
 'sample_000516/params.json',
 'sample_000517/params.json',
 'sample_000518/params.json',
 'sample_000519/params.json',
 'sample_000520/params.json',
 'sample_000521/params.json',
 'sample_000522/params.json',
 'sample_000523/params.json',
 'sample_000524/params.json',
 'sample_000525/params.json',
 'sample_000526/params.json',
 'sample_000527/params.json',
 'sample_000528/params.json',
 'sample_000529/params.json',
 'sample_000530/params.json',
 'sample_000531/params.json',
 'sample_000532/params.json',
 'sample_000533/params.json',
 'sample_000534/params.json',
 'sample_000535/params.json',
 'sample_000536/params.json',
 'sample_000537/params.json',
 'sample_000538/params.json',
 'sample_000539/params.json',
 'sample_000540/params.json',
 'sample_000541/params.json',
 'sample_000542/params.json',
 'sample_000543/params.json',
 'sample_000544/params.json',
 'sample_000545/params.json',
 'sample_000546/params.json',
 'sample_000547/params.json',
 'sample_000548/params.json',
 'sample_000549/params.json',
 'sample_000550/params.json',
 'sample_000551/params.json',
 'sample_000552/params.json',
 'sample_000553/params.json',
 'sample_000554/params.json',
 'sample_000555/params.json',
 'sample_000556/params.json',
 'sample_000557/params.json',
 'sample_000558/params.json',
 'sample_000559/params.json',
 'sample_000560/params.json',
 'sample_000561/params.json',
 'sample_000562/params.json',
 'sample_000563/params.json',
 'sample_000564/params.json',
 'sample_000565/params.json',
 'sample_000566/params.json',
 'sample_000567/params.json',
 'sample_000568/params.json',
 'sample_000569/params.json',
 'sample_000570/params.json',
 'sample_000571/params.json',
 'sample_000572/params.json',
 'sample_000573/params.json',
 'sample_000574/params.json',
 'sample_000575/params.json',
 'sample_000576/params.json',
 'sample_000577/params.json',
 'sample_000578/params.json',
 'sample_000579/params.json',
 'sample_000580/params.json',
 'sample_000581/params.json',
 'sample_000582/params.json',
 'sample_000583/params.json',
 'sample_000584/params.json',
 'sample_000585/params.json',
 'sample_000586/params.json',
 'sample_000587/params.json',
 'sample_000588/params.json',
 'sample_000589/params.json',
 'sample_000590/params.json',
 'sample_000591/params.json',
 'sample_000592/params.json',
 'sample_000593/params.json',
 'sample_000594/params.json',
 'sample_000595/params.json',
 'sample_000596/params.json',
 'sample_000597/params.json',
 'sample_000598/params.json',
 'sample_000599/params.json',
 'sample_000600/params.json',
 'sample_000601/params.json',
 'sample_000602/params.json',
 'sample_000603/params.json',
 'sample_000604/params.json',
 'sample_000605/params.json',
 'sample_000606/params.json',
 'sample_000607/params.json',
 'sample_000608/params.json',
 'sample_000609/params.json',
 'sample_000610/params.json',
 'sample_000611/params.json',
 'sample_000612/params.json',
 'sample_000613/params.json',
 'sample_000614/params.json',
 'sample_000615/params.json',
 'sample_000616/params.json',
 'sample_000617/params.json',
 'sample_000618/params.json',
 'sample_000619/params.json',
 'sample_000620/params.json',
 'sample_000621/params.json',
 'sample_000622/params.json',
 'sample_000623/params.json',
 'sample_000624/params.json',
 'sample_000625/params.json',
 'sample_000626/params.json',
 'sample_000627/params.json',
 'sample_000628/params.json',
 'sample_000629/params.json',
 'sample_000630/params.json',
 'sample_000631/params.json',
 'sample_000632/params.json',
 'sample_000633/params.json',
 'sample_000634/params.json',
 'sample_000635/params.json',
 'sample_000636/params.json',
 'sample_000637/params.json',
 'sample_000638/params.json',
 'sample_000639/params.json',
 'sample_000640/params.json',
 'sample_000641/params.json',
 'sample_000642/params.json',
 'sample_000643/params.json',
 'sample_000644/params.json',
 'sample_000645/params.json',
 'sample_000646/params.json',
 'sample_000647/params.json',
 'sample_000648/params.json',
 'sample_000649/params.json',
 'sample_000650/params.json',
 'sample_000651/params.json',
 'sample_000652/params.json',
 'sample_000653/params.json',
 'sample_000654/params.json',
 'sample_000655/params.json',
 'sample_000656/params.json',
 'sample_000657/params.json',
 'sample_000658/params.json',
 'sample_000659/params.json',
 'sample_000660/params.json',
 'sample_000661/params.json',
 'sample_000662/params.json',
 'sample_000663/params.json',
 'sample_000664/params.json',
 'sample_000665/params.json',
 'sample_000666/params.json',

In [ ]:
# for f in params_json_files:
# hf_hub_download(repo_id=REPO_ID, token=HF_TOKEN,filename=f,local_dir=METADATA_DIR, repo_type="dataset")
print("works")

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

### Read and Cast data

In [8]:
# Find all params.json files under pump_metadata
json_paths = sorted(glob.glob(os.path.join(METADATA_DIR, "sample_*", "params.json")))

# Load all json data into a list of dicts
records = []
for path in json_paths:
    with open(path, "r") as f:
        data = json.load(f)
        # Add the folder name as sample_id
        data["sample_id"] = os.path.basename(os.path.dirname(path))
        records.append(data)

# Create polars DataFrame
df = pl.DataFrame(records)

# Define column groupings for typing
float_cols = [
    "flow_rate",
    "head",
    "outer_diameter_factor",
    "outlet_width_factor",
    "shroud_diameter_factor",
    "volute_q_factor",
    "volute_r_factor",
    "teAngleDelta",
    "leAngleDelta",
    "compactness",
    "leWidthVar",
    "leRake",
    "teRake",
    "flow_rate_op_condition",
    "leShapevar",
    "shrAngleVar",
    "stream_velocity",
    "area_ref",
    "length_ref",
    "length_ref_pitch",
    "length_ref_roll",
    "length_ref_yaw",
    "moment_center_x",
    "moment_center_y",
    "moment_center_z",
    "R",
    "gamma",
    "cp",
    "air_density",
]

int_cols = [
    "rotational_speed",
    "fix_blade_number",
    "leAngleVar",
    "leShapeVar",
    "tipGap",
    "leEllipseFactor",
    "mach",
    "pressure",
    "temperature",
]

bool_cols = ["teTangential"]

# Apply casting expressions
cast_exprs = []

for col in float_cols:
    if col in df.columns:
        cast_exprs.append(pl.col(col).cast(pl.Float64))

for col in int_cols:
    if col in df.columns:
        cast_exprs.append(pl.col(col).cast(pl.Int64))

for col in bool_cols:
    if col in df.columns:
        # Handle string "true"/"false" safely
        if df[col].dtype == pl.String:
            cast_exprs.append(
                (pl.col(col).str.to_lowercase() == "true").cast(pl.Boolean)
            )
        else:
            cast_exprs.append(pl.col(col).cast(pl.Boolean))

df = df.with_columns(cast_exprs)

In [9]:
df.head()

shape: (5, 40)
┌──────────────┬───────────┬──────────┬─────────────┬───┬─────────┬───────┬──────────┬─────────────┐
│ rotational_s ┆ flow_rate ┆ head     ┆ outer_diame ┆ … ┆ R       ┆ gamma ┆ cp       ┆ sample_id   │
│ peed         ┆ ---       ┆ ---      ┆ ter_factor  ┆   ┆ ---     ┆ ---   ┆ ---      ┆ ---         │
│ ---          ┆ f64       ┆ f64      ┆ ---         ┆   ┆ f64     ┆ f64   ┆ f64      ┆ str         │
│ i64          ┆           ┆          ┆ f64         ┆   ┆         ┆       ┆          ┆             │
╞══════════════╪═══════════╪══════════╪═════════════╪═══╪═════════╪═══════╪══════════╪═════════════╡
│ 1750         ┆ 237.5275  ┆ 101.7615 ┆ 0.9626      ┆ … ┆ 287.058 ┆ 1.4   ┆ 1004.703 ┆ sample_0000 │
│              ┆           ┆          ┆             ┆   ┆         ┆       ┆          ┆ 01          │
│ 1750         ┆ 506.8698  ┆ 91.4494  ┆ 0.9959      ┆ … ┆ 287.058 ┆ 1.4   ┆ 1004.703 ┆ sample_0000 │
│              ┆           ┆          ┆             ┆   ┆         ┆       ┆          ┆ 02          │
│ 1750         ┆ 1395.8313 ┆ 25.7733  ┆ 0.9685      ┆ … ┆ 287.058 ┆ 1.4   ┆ 1004.703 ┆ sample_0000 │
│              ┆           ┆          ┆             ┆   ┆         ┆       ┆          ┆ 03          │
│ 1750         ┆ 195.5574  ┆ 49.1195  ┆ 0.9677      ┆ … ┆ 287.058 ┆ 1.4   ┆ 1004.703 ┆ sample_0000 │
│              ┆           ┆          ┆             ┆   ┆         ┆       ┆          ┆ 04          │
│ 1750         ┆ 497.1165  ┆ 126.8548 ┆ 0.9575      ┆ … ┆ 287.058 ┆ 1.4   ┆ 1004.703 ┆ sample_0000 │
│              ┆           ┆          ┆             ┆   ┆         ┆       ┆          ┆ 05          │
└──────────────┴───────────┴──────────┴─────────────┴───┴─────────┴───────┴──────────┴─────────────┘

In [10]:
df.describe()

shape: (9, 41)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬────────┬────────────┬───────────┐
│ statistic  ┆ rotational ┆ flow_rate  ┆ head      ┆ … ┆ R       ┆ gamma  ┆ cp         ┆ sample_id │
│ ---        ┆ _speed     ┆ ---        ┆ ---       ┆   ┆ ---     ┆ ---    ┆ ---        ┆ ---       │
│ str        ┆ ---        ┆ f64        ┆ f64       ┆   ┆ f64     ┆ f64    ┆ f64        ┆ str       │
│            ┆ f64        ┆            ┆           ┆   ┆         ┆        ┆            ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪════════╪════════════╪═══════════╡
│ count      ┆ 5637.0     ┆ 5637.0     ┆ 5637.0    ┆ … ┆ 5637.0  ┆ 5637.0 ┆ 5637.0     ┆ 5637      │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ … ┆ 0.0     ┆ 0.0    ┆ 0.0        ┆ 0         │
│ mean       ┆ 1750.0     ┆ 631.775682 ┆ 67.395113 ┆ … ┆ 287.058 ┆ 1.4    ┆ 1004.703   ┆ null      │
│ std        ┆ 0.0        ┆ 431.89182  ┆ 33.342899 ┆ … ┆ 0.0     ┆ 0.0    ┆ 4.7888e-15 ┆ null      │
│ min        ┆ 1750.0     ┆ 17.0063    ┆ 5.159     ┆ … ┆ 287.058 ┆ 1.4    ┆ 1004.703   ┆ sample_00 │
│            ┆            ┆            ┆           ┆   ┆         ┆        ┆            ┆ 0001      │
│ 25%        ┆ 1750.0     ┆ 291.6982   ┆ 38.8625   ┆ … ┆ 287.058 ┆ 1.4    ┆ 1004.703   ┆ null      │
│ 50%        ┆ 1750.0     ┆ 506.8925   ┆ 65.8328   ┆ … ┆ 287.058 ┆ 1.4    ┆ 1004.703   ┆ null      │
│ 75%        ┆ 1750.0     ┆ 949.0717   ┆ 95.1345   ┆ … ┆ 287.058 ┆ 1.4    ┆ 1004.703   ┆ null      │
│ max        ┆ 1750.0     ┆ 1599.2509  ┆ 129.986   ┆ … ┆ 287.058 ┆ 1.4    ┆ 1004.703   ┆ sample_00 │
│            ┆            ┆            ┆           ┆   ┆         ┆        ┆            ┆ 5646      │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴────────┴────────────┴───────────┘

### Applying Kennard-Stone to select most distinct geometries

In [11]:
# 1. Define the geometric columns to include in the shape analysis
active_geometric_cols = [
    "outer_diameter_factor",
    "outlet_width_factor",
    "shroud_diameter_factor",
    "teAngleDelta",
    "leAngleDelta",
    "compactness",
    "leWidthVar",
    "leRake",
    "teRake",
    "leShapevar",
]

# Ensure we only use columns that actually exist in the DataFrame
existing_geo_cols = [col for col in active_geometric_cols if col in df.columns]

# 2. Extract features, fill missing/null values, and cast booleans to floats
df_features = (
    df.select(existing_geo_cols)
    .with_columns(
        [
            # Cast boolean columns (like teTangential) to floats so they can be scaled
            pl.col(col).cast(pl.Float64)
            for col in existing_geo_cols
        ]
    )
    .fill_null(0.0)
)

X = df_features.to_numpy()

# 3. Scale features (essential so that features with larger ranges don't dominate the distance)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. Use the Kennard-Stone algorithm to select a diverse subset
# Set train_size to the number of shapes you want to download/encoder-fine-tune
num_to_select = 200

X_train, X_test, df_selected, df_remaining = ks.train_test_split(
    X_scaled, df, train_size=num_to_select
)

# 5. Output the selected sample folder names
selected_folders = df_selected["sample_id"].to_list()

print(f"Selected {len(selected_folders)} diverse shapes:")
print(selected_folders)

2026-07-10 11:12:26,705 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-07-10 11:12:27,377 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

Selected 200 diverse shapes:
['sample_002231', 'sample_002089', 'sample_003959', 'sample_001469', 'sample_000343', 'sample_001281', 'sample_000291', 'sample_001590', 'sample_001561', 'sample_001575', 'sample_001212', 'sample_001806', 'sample_004644', 'sample_004314', 'sample_004759', 'sample_001148', 'sample_003691', 'sample_000665', 'sample_003755', 'sample_001294', 'sample_001433', 'sample_000140', 'sample_000724', 'sample_001221', 'sample_003348', 'sample_002686', 'sample_000107', 'sample_003269', 'sample_002208', 'sample_003604', 'sample_000198', 'sample_001778', 'sample_002317', 'sample_002302', 'sample_001878', 'sample_004702', 'sample_000277', 'sample_002533', 'sample_000327', 'sample_001501', 'sample_000286', 'sample_001471', 'sample_000627', 'sample_000749', 'sample_000615', 'sample_002164', 'sample_001270', 'sample_001311', 'sample_002052', 'sample_000063', 'sample_002333', 'sample_000295', 'sample_004135', 'sample_000430', 'sample_001809', 'sample_000891', 'sample_000185', 'sample_001265', 'sample_001094', 'sample_004040', 'sample_000486', 'sample_001193', 'sample_003865', 'sample_001953', 'sample_001272', 'sample_001129', 'sample_003287', 'sample_002117', 'sample_002853', 'sample_003674', 'sample_001788', 'sample_003188', 'sample_001509', 'sample_001253', 'sample_000964', 'sample_000313', 'sample_002344', 'sample_004219', 'sample_000742', 'sample_003679', 'sample_002157', 'sample_004118', 'sample_002187', 'sample_001870', 'sample_000894', 'sample_000444', 'sample_004869', 'sample_000019', 'sample_001514', 'sample_004520', 'sample_002276', 'sample_000595', 'sample_000405', 'sample_000497', 'sample_004927', 'sample_002478', 'sample_002332', 'sample_001009', 'sample_000816', 'sample_003510', 'sample_001186', 'sample_000858', 'sample_001573', 'sample_000886', 'sample_000519', 'sample_004737', 'sample_003954', 'sample_003392', 'sample_000608', 'sample_001440', 'sample_004551', 'sample_003543', 'sample_002209', 'sample_001472', 'sample_000873', 'sample_001190', 'sample_002976', 'sample_002475', 'sample_002897', 'sample_003618', 'sample_000022', 'sample_000242', 'sample_005414', 'sample_000624', 'sample_001549', 'sample_004376', 'sample_005245', 'sample_001006', 'sample_000256', 'sample_001504', 'sample_005641', 'sample_000798', 'sample_001538', 'sample_000707', 'sample_000994', 'sample_000760', 'sample_002367', 'sample_002088', 'sample_000132', 'sample_002348', 'sample_002619', 'sample_003268', 'sample_004575', 'sample_005054', 'sample_003420', 'sample_001995', 'sample_005327', 'sample_000672', 'sample_005241', 'sample_001192', 'sample_004543', 'sample_001693', 'sample_003016', 'sample_001742', 'sample_002993', 'sample_004123', 'sample_002687', 'sample_002774', 'sample_003523', 'sample_000159', 'sample_002122', 'sample_003088', 'sample_004855', 'sample_003321', 'sample_004743', 'sample_005466', 'sample_001673', 'sample_001064', 'sample_001634', 'sample_001088', 'sample_005277', 'sample_002521', 'sample_001361', 'sample_001477', 'sample_002639', 'sample_004210', 'sample_002372', 'sample_001343', 'sample_002441', 'sample_002964', 'sample_005376', 'sample_003811', 'sample_005073', 'sample_002574', 'sample_003328', 'sample_000333', 'sample_000541', 'sample_000484', 'sample_000908', 'sample_004808', 'sample_005204', 'sample_004411', 'sample_000153', 'sample_002042', 'sample_003200', 'sample_001718', 'sample_002392', 'sample_004271', 'sample_000422', 'sample_004237']

In [13]:
df_filtered = df_selected.filter(pl.col("sample_id").is_in(selected_folders))
df_filtered.select(active_geometric_cols).describe()

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ outer_dia ┆ outlet_wi ┆ shroud_di ┆ … ┆ leWidthVa ┆ leRake   ┆ teRake    ┆ leShapeva │
│ ---       ┆ meter_fac ┆ dth_facto ┆ ameter_fa ┆   ┆ r         ┆ ---      ┆ ---       ┆ r         │
│ str       ┆ tor       ┆ r         ┆ ctor      ┆   ┆ ---       ┆ f64      ┆ f64       ┆ ---       │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆          ┆           ┆ f64       │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 200.0     ┆ 200.0     ┆ 200.0     ┆ … ┆ 200.0     ┆ 200.0    ┆ 200.0     ┆ 200.0     │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ 0.975348  ┆ 0.998496  ┆ 1.0763075 ┆ … ┆ 1.000147  ┆ 9.790015 ┆ 10.058493 ┆ 0.144926  │
│ std       ┆ 0.017357  ┆ 0.068568  ┆ 0.050778  ┆ … ┆ 0.068701  ┆ 6.686674 ┆ 6.655577  ┆ 0.103324  │
│ min       ┆ 0.9501    ┆ 0.9002    ┆ 1.0002    ┆ … ┆ 0.9       ┆ 0.0749   ┆ 0.0085    ┆ 0.0002    │
│ 25%       ┆ 0.9584    ┆ 0.9281    ┆ 1.0273    ┆ … ┆ 0.9315    ┆ 3.0698   ┆ 3.3927    ┆ 0.0442    │
│ 50%       ┆ 0.9745    ┆ 1.0025    ┆ 1.0772    ┆ … ┆ 1.0008    ┆ 10.7351  ┆ 10.4506   ┆ 0.1423    │
│ 75%       ┆ 0.9938    ┆ 1.065     ┆ 1.1284    ┆ … ┆ 1.07      ┆ 16.1506  ┆ 16.2815   ┆ 0.2448    │
│ max       ┆ 0.9998    ┆ 1.0994    ┆ 1.15      ┆ … ┆ 1.0991    ┆ 19.9997  ┆ 19.9917   ┆ 0.2997    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

### Download selected pumps

In [14]:
all_files
pump_stl_selected_files = [
    f
    for f in all_files
    if (f.endswith(".stl") and (f.split("/")[0] in selected_folders))
]

In [15]:
pump_stl_selected_files[:5]

['sample_000019/merged_surfaces.stl',
 'sample_000022/merged_surfaces.stl',
 'sample_000063/merged_surfaces.stl',
 'sample_000107/merged_surfaces.stl',
 'sample_000132/merged_surfaces.stl']

In [16]:
# Iterate and download each selected STL file
for idx, f in enumerate(pump_stl_selected_files, 1):
    print(f"[{idx}/{len(pump_stl_selected_files)}] Downloading: {f}")
    try:
        hf_hub_download(
            repo_id=REPO_ID,
            token=HF_TOKEN,
            filename=f,
            local_dir=METADATA_DIR,
            repo_type="dataset",
        )
    except Exception as e:
        print(f"Failed to download {f}: {e}")

[1/200] Downloading: sample_000019/merged_surfaces.stl
[2/200] Downloading: sample_000022/merged_surfaces.stl
[3/200] Downloading: sample_000063/merged_surfaces.stl
[4/200] Downloading: sample_000107/merged_surfaces.stl
[5/200] Downloading: sample_000132/merged_surfaces.stl
[6/200] Downloading: sample_000140/merged_surfaces.stl
[7/200] Downloading: sample_000153/merged_surfaces.stl
[8/200] Downloading: sample_000159/merged_surfaces.stl
[9/200] Downloading: sample_000185/merged_surfaces.stl

sample_000185/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[10/200] Downloading: sample_000198/merged_surfaces.stl

sample_000198/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[11/200] Downloading: sample_000242/merged_surfaces.stl

sample_000242/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[12/200] Downloading: sample_000256/merged_surfaces.stl

sample_000256/merged_surfaces.stl:   0%|          | 0.00/31.3M [00:00<?, ?B/s]

[13/200] Downloading: sample_000277/merged_surfaces.stl

sample_000277/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[14/200] Downloading: sample_000286/merged_surfaces.stl

sample_000286/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[15/200] Downloading: sample_000291/merged_surfaces.stl

sample_000291/merged_surfaces.stl:   0%|          | 0.00/31.3M [00:00<?, ?B/s]

[16/200] Downloading: sample_000295/merged_surfaces.stl

sample_000295/merged_surfaces.stl:   0%|          | 0.00/30.9M [00:00<?, ?B/s]

[17/200] Downloading: sample_000313/merged_surfaces.stl

sample_000313/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[18/200] Downloading: sample_000327/merged_surfaces.stl

sample_000327/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[19/200] Downloading: sample_000333/merged_surfaces.stl

sample_000333/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[20/200] Downloading: sample_000343/merged_surfaces.stl

sample_000343/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[21/200] Downloading: sample_000405/merged_surfaces.stl

sample_000405/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[22/200] Downloading: sample_000422/merged_surfaces.stl

sample_000422/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[23/200] Downloading: sample_000430/merged_surfaces.stl

sample_000430/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[24/200] Downloading: sample_000444/merged_surfaces.stl

sample_000444/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[25/200] Downloading: sample_000484/merged_surfaces.stl

sample_000484/merged_surfaces.stl:   0%|          | 0.00/30.5M [00:00<?, ?B/s]

[26/200] Downloading: sample_000486/merged_surfaces.stl

sample_000486/merged_surfaces.stl:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

[27/200] Downloading: sample_000497/merged_surfaces.stl

sample_000497/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[28/200] Downloading: sample_000519/merged_surfaces.stl

sample_000519/merged_surfaces.stl:   0%|          | 0.00/30.3M [00:00<?, ?B/s]

[29/200] Downloading: sample_000541/merged_surfaces.stl

sample_000541/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[30/200] Downloading: sample_000595/merged_surfaces.stl

sample_000595/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[31/200] Downloading: sample_000608/merged_surfaces.stl

sample_000608/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[32/200] Downloading: sample_000615/merged_surfaces.stl

sample_000615/merged_surfaces.stl:   0%|          | 0.00/26.7M [00:00<?, ?B/s]

[33/200] Downloading: sample_000624/merged_surfaces.stl

sample_000624/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[34/200] Downloading: sample_000627/merged_surfaces.stl

sample_000627/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[35/200] Downloading: sample_000665/merged_surfaces.stl

sample_000665/merged_surfaces.stl:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

[36/200] Downloading: sample_000672/merged_surfaces.stl

sample_000672/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[37/200] Downloading: sample_000707/merged_surfaces.stl

sample_000707/merged_surfaces.stl:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

[38/200] Downloading: sample_000724/merged_surfaces.stl

sample_000724/merged_surfaces.stl:   0%|          | 0.00/30.8M [00:00<?, ?B/s]

[39/200] Downloading: sample_000742/merged_surfaces.stl

sample_000742/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[40/200] Downloading: sample_000749/merged_surfaces.stl

sample_000749/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[41/200] Downloading: sample_000760/merged_surfaces.stl

sample_000760/merged_surfaces.stl:   0%|          | 0.00/26.8M [00:00<?, ?B/s]

[42/200] Downloading: sample_000798/merged_surfaces.stl

sample_000798/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[43/200] Downloading: sample_000816/merged_surfaces.stl

sample_000816/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[44/200] Downloading: sample_000858/merged_surfaces.stl

sample_000858/merged_surfaces.stl:   0%|          | 0.00/30.7M [00:00<?, ?B/s]

[45/200] Downloading: sample_000873/merged_surfaces.stl

sample_000873/merged_surfaces.stl:   0%|          | 0.00/31.5M [00:00<?, ?B/s]

[46/200] Downloading: sample_000886/merged_surfaces.stl

sample_000886/merged_surfaces.stl:   0%|          | 0.00/31.8M [00:00<?, ?B/s]

[47/200] Downloading: sample_000891/merged_surfaces.stl

sample_000891/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[48/200] Downloading: sample_000894/merged_surfaces.stl

sample_000894/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[49/200] Downloading: sample_000908/merged_surfaces.stl

sample_000908/merged_surfaces.stl:   0%|          | 0.00/30.3M [00:00<?, ?B/s]

[50/200] Downloading: sample_000964/merged_surfaces.stl

sample_000964/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[51/200] Downloading: sample_000994/merged_surfaces.stl

sample_000994/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[52/200] Downloading: sample_001006/merged_surfaces.stl

sample_001006/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[53/200] Downloading: sample_001009/merged_surfaces.stl

sample_001009/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[54/200] Downloading: sample_001064/merged_surfaces.stl

sample_001064/merged_surfaces.stl:   0%|          | 0.00/31.4M [00:00<?, ?B/s]

[55/200] Downloading: sample_001088/merged_surfaces.stl

sample_001088/merged_surfaces.stl:   0%|          | 0.00/26.7M [00:00<?, ?B/s]

[56/200] Downloading: sample_001094/merged_surfaces.stl

sample_001094/merged_surfaces.stl:   0%|          | 0.00/25.3M [00:00<?, ?B/s]

[57/200] Downloading: sample_001129/merged_surfaces.stl

sample_001129/merged_surfaces.stl:   0%|          | 0.00/30.9M [00:00<?, ?B/s]

[58/200] Downloading: sample_001148/merged_surfaces.stl

sample_001148/merged_surfaces.stl:   0%|          | 0.00/27.5M [00:00<?, ?B/s]

[59/200] Downloading: sample_001186/merged_surfaces.stl

sample_001186/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[60/200] Downloading: sample_001190/merged_surfaces.stl

sample_001190/merged_surfaces.stl:   0%|          | 0.00/32.3M [00:00<?, ?B/s]

[61/200] Downloading: sample_001192/merged_surfaces.stl

sample_001192/merged_surfaces.stl:   0%|          | 0.00/26.4M [00:00<?, ?B/s]

[62/200] Downloading: sample_001193/merged_surfaces.stl

sample_001193/merged_surfaces.stl:   0%|          | 0.00/28.3M [00:00<?, ?B/s]

[63/200] Downloading: sample_001212/merged_surfaces.stl

sample_001212/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[64/200] Downloading: sample_001221/merged_surfaces.stl

sample_001221/merged_surfaces.stl:   0%|          | 0.00/27.5M [00:00<?, ?B/s]

[65/200] Downloading: sample_001253/merged_surfaces.stl

sample_001253/merged_surfaces.stl:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

[66/200] Downloading: sample_001265/merged_surfaces.stl

sample_001265/merged_surfaces.stl:   0%|          | 0.00/24.4M [00:00<?, ?B/s]

[67/200] Downloading: sample_001270/merged_surfaces.stl

sample_001270/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[68/200] Downloading: sample_001272/merged_surfaces.stl

sample_001272/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[69/200] Downloading: sample_001281/merged_surfaces.stl

sample_001281/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[70/200] Downloading: sample_001294/merged_surfaces.stl

sample_001294/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[71/200] Downloading: sample_001311/merged_surfaces.stl

sample_001311/merged_surfaces.stl:   0%|          | 0.00/26.8M [00:00<?, ?B/s]

[72/200] Downloading: sample_001343/merged_surfaces.stl

sample_001343/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[73/200] Downloading: sample_001361/merged_surfaces.stl

sample_001361/merged_surfaces.stl:   0%|          | 0.00/26.4M [00:00<?, ?B/s]

[74/200] Downloading: sample_001433/merged_surfaces.stl

sample_001433/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[75/200] Downloading: sample_001440/merged_surfaces.stl

sample_001440/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[76/200] Downloading: sample_001469/merged_surfaces.stl

sample_001469/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[77/200] Downloading: sample_001471/merged_surfaces.stl

sample_001471/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[78/200] Downloading: sample_001472/merged_surfaces.stl

sample_001472/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[79/200] Downloading: sample_001477/merged_surfaces.stl

sample_001477/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[80/200] Downloading: sample_001501/merged_surfaces.stl

sample_001501/merged_surfaces.stl:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

[81/200] Downloading: sample_001504/merged_surfaces.stl

sample_001504/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[82/200] Downloading: sample_001509/merged_surfaces.stl

sample_001509/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[83/200] Downloading: sample_001514/merged_surfaces.stl

sample_001514/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[84/200] Downloading: sample_001538/merged_surfaces.stl

sample_001538/merged_surfaces.stl:   0%|          | 0.00/28.6M [00:00<?, ?B/s]

[85/200] Downloading: sample_001549/merged_surfaces.stl

sample_001549/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[86/200] Downloading: sample_001561/merged_surfaces.stl

sample_001561/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[87/200] Downloading: sample_001573/merged_surfaces.stl

sample_001573/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[88/200] Downloading: sample_001575/merged_surfaces.stl

sample_001575/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[89/200] Downloading: sample_001590/merged_surfaces.stl

sample_001590/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[90/200] Downloading: sample_001634/merged_surfaces.stl

sample_001634/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[91/200] Downloading: sample_001673/merged_surfaces.stl

sample_001673/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[92/200] Downloading: sample_001693/merged_surfaces.stl

sample_001693/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[93/200] Downloading: sample_001718/merged_surfaces.stl

sample_001718/merged_surfaces.stl:   0%|          | 0.00/26.8M [00:00<?, ?B/s]

[94/200] Downloading: sample_001742/merged_surfaces.stl

sample_001742/merged_surfaces.stl:   0%|          | 0.00/30.8M [00:00<?, ?B/s]

[95/200] Downloading: sample_001778/merged_surfaces.stl

sample_001778/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[96/200] Downloading: sample_001788/merged_surfaces.stl

sample_001788/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[97/200] Downloading: sample_001806/merged_surfaces.stl

sample_001806/merged_surfaces.stl:   0%|          | 0.00/26.1M [00:00<?, ?B/s]

[98/200] Downloading: sample_001809/merged_surfaces.stl

sample_001809/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[99/200] Downloading: sample_001870/merged_surfaces.stl

sample_001870/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[100/200] Downloading: sample_001878/merged_surfaces.stl

sample_001878/merged_surfaces.stl:   0%|          | 0.00/26.1M [00:00<?, ?B/s]

[101/200] Downloading: sample_001953/merged_surfaces.stl

sample_001953/merged_surfaces.stl:   0%|          | 0.00/26.1M [00:00<?, ?B/s]

[102/200] Downloading: sample_001995/merged_surfaces.stl

sample_001995/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[103/200] Downloading: sample_002042/merged_surfaces.stl

sample_002042/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[104/200] Downloading: sample_002052/merged_surfaces.stl

sample_002052/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[105/200] Downloading: sample_002088/merged_surfaces.stl

sample_002088/merged_surfaces.stl:   0%|          | 0.00/28.9M [00:00<?, ?B/s]

[106/200] Downloading: sample_002089/merged_surfaces.stl

sample_002089/merged_surfaces.stl:   0%|          | 0.00/25.4M [00:00<?, ?B/s]

[107/200] Downloading: sample_002117/merged_surfaces.stl

sample_002117/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[108/200] Downloading: sample_002122/merged_surfaces.stl

sample_002122/merged_surfaces.stl:   0%|          | 0.00/32.7M [00:00<?, ?B/s]

[109/200] Downloading: sample_002157/merged_surfaces.stl

sample_002157/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[110/200] Downloading: sample_002164/merged_surfaces.stl

sample_002164/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[111/200] Downloading: sample_002187/merged_surfaces.stl

sample_002187/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[112/200] Downloading: sample_002208/merged_surfaces.stl

sample_002208/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[113/200] Downloading: sample_002209/merged_surfaces.stl

sample_002209/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[114/200] Downloading: sample_002231/merged_surfaces.stl

sample_002231/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[115/200] Downloading: sample_002276/merged_surfaces.stl

sample_002276/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[116/200] Downloading: sample_002302/merged_surfaces.stl

sample_002302/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[117/200] Downloading: sample_002317/merged_surfaces.stl

sample_002317/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[118/200] Downloading: sample_002332/merged_surfaces.stl

sample_002332/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[119/200] Downloading: sample_002333/merged_surfaces.stl

sample_002333/merged_surfaces.stl:   0%|          | 0.00/30.2M [00:00<?, ?B/s]

[120/200] Downloading: sample_002344/merged_surfaces.stl

sample_002344/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[121/200] Downloading: sample_002348/merged_surfaces.stl

sample_002348/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[122/200] Downloading: sample_002367/merged_surfaces.stl

sample_002367/merged_surfaces.stl:   0%|          | 0.00/27.5M [00:00<?, ?B/s]

[123/200] Downloading: sample_002372/merged_surfaces.stl

sample_002372/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[124/200] Downloading: sample_002392/merged_surfaces.stl

sample_002392/merged_surfaces.stl:   0%|          | 0.00/28.6M [00:00<?, ?B/s]

[125/200] Downloading: sample_002441/merged_surfaces.stl

sample_002441/merged_surfaces.stl:   0%|          | 0.00/27.1M [00:00<?, ?B/s]

[126/200] Downloading: sample_002475/merged_surfaces.stl

sample_002475/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[127/200] Downloading: sample_002478/merged_surfaces.stl

sample_002478/merged_surfaces.stl:   0%|          | 0.00/30.2M [00:00<?, ?B/s]

[128/200] Downloading: sample_002521/merged_surfaces.stl

sample_002521/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[129/200] Downloading: sample_002533/merged_surfaces.stl

sample_002533/merged_surfaces.stl:   0%|          | 0.00/28.9M [00:00<?, ?B/s]

[130/200] Downloading: sample_002574/merged_surfaces.stl

sample_002574/merged_surfaces.stl:   0%|          | 0.00/30.9M [00:00<?, ?B/s]

[131/200] Downloading: sample_002619/merged_surfaces.stl

sample_002619/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[132/200] Downloading: sample_002639/merged_surfaces.stl

sample_002639/merged_surfaces.stl:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

[133/200] Downloading: sample_002686/merged_surfaces.stl

sample_002686/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[134/200] Downloading: sample_002687/merged_surfaces.stl

sample_002687/merged_surfaces.stl:   0%|          | 0.00/30.9M [00:00<?, ?B/s]

[135/200] Downloading: sample_002774/merged_surfaces.stl

sample_002774/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[136/200] Downloading: sample_002853/merged_surfaces.stl

sample_002853/merged_surfaces.stl:   0%|          | 0.00/26.2M [00:00<?, ?B/s]

[137/200] Downloading: sample_002897/merged_surfaces.stl

sample_002897/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[138/200] Downloading: sample_002964/merged_surfaces.stl

sample_002964/merged_surfaces.stl:   0%|          | 0.00/26.9M [00:00<?, ?B/s]

[139/200] Downloading: sample_002976/merged_surfaces.stl

sample_002976/merged_surfaces.stl:   0%|          | 0.00/27.3M [00:00<?, ?B/s]

[140/200] Downloading: sample_002993/merged_surfaces.stl

sample_002993/merged_surfaces.stl:   0%|          | 0.00/26.3M [00:00<?, ?B/s]

[141/200] Downloading: sample_003016/merged_surfaces.stl

sample_003016/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[142/200] Downloading: sample_003088/merged_surfaces.stl

sample_003088/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[143/200] Downloading: sample_003188/merged_surfaces.stl

sample_003188/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[144/200] Downloading: sample_003200/merged_surfaces.stl

sample_003200/merged_surfaces.stl:   0%|          | 0.00/31.5M [00:00<?, ?B/s]

[145/200] Downloading: sample_003268/merged_surfaces.stl

sample_003268/merged_surfaces.stl:   0%|          | 0.00/27.3M [00:00<?, ?B/s]

[146/200] Downloading: sample_003269/merged_surfaces.stl

sample_003269/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[147/200] Downloading: sample_003287/merged_surfaces.stl

sample_003287/merged_surfaces.stl:   0%|          | 0.00/25.9M [00:00<?, ?B/s]

[148/200] Downloading: sample_003321/merged_surfaces.stl

sample_003321/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[149/200] Downloading: sample_003328/merged_surfaces.stl

sample_003328/merged_surfaces.stl:   0%|          | 0.00/26.1M [00:00<?, ?B/s]

[150/200] Downloading: sample_003348/merged_surfaces.stl

sample_003348/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[151/200] Downloading: sample_003392/merged_surfaces.stl

sample_003392/merged_surfaces.stl:   0%|          | 0.00/30.2M [00:00<?, ?B/s]

[152/200] Downloading: sample_003420/merged_surfaces.stl

sample_003420/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[153/200] Downloading: sample_003510/merged_surfaces.stl

sample_003510/merged_surfaces.stl:   0%|          | 0.00/26.7M [00:00<?, ?B/s]

[154/200] Downloading: sample_003523/merged_surfaces.stl

sample_003523/merged_surfaces.stl:   0%|          | 0.00/31.1M [00:00<?, ?B/s]

[155/200] Downloading: sample_003543/merged_surfaces.stl

sample_003543/merged_surfaces.stl:   0%|          | 0.00/31.0M [00:00<?, ?B/s]

[156/200] Downloading: sample_003604/merged_surfaces.stl

sample_003604/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[157/200] Downloading: sample_003618/merged_surfaces.stl

sample_003618/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[158/200] Downloading: sample_003674/merged_surfaces.stl

sample_003674/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[159/200] Downloading: sample_003679/merged_surfaces.stl

sample_003679/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[160/200] Downloading: sample_003691/merged_surfaces.stl

sample_003691/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[161/200] Downloading: sample_003755/merged_surfaces.stl

sample_003755/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[162/200] Downloading: sample_003811/merged_surfaces.stl

sample_003811/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[163/200] Downloading: sample_003865/merged_surfaces.stl

sample_003865/merged_surfaces.stl:   0%|          | 0.00/29.3M [00:00<?, ?B/s]

[164/200] Downloading: sample_003954/merged_surfaces.stl

sample_003954/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[165/200] Downloading: sample_003959/merged_surfaces.stl

sample_003959/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[166/200] Downloading: sample_004040/merged_surfaces.stl

sample_004040/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[167/200] Downloading: sample_004118/merged_surfaces.stl

sample_004118/merged_surfaces.stl:   0%|          | 0.00/28.9M [00:00<?, ?B/s]

[168/200] Downloading: sample_004123/merged_surfaces.stl

sample_004123/merged_surfaces.stl:   0%|          | 0.00/29.3M [00:00<?, ?B/s]

[169/200] Downloading: sample_004135/merged_surfaces.stl

sample_004135/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[170/200] Downloading: sample_004210/merged_surfaces.stl

sample_004210/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[171/200] Downloading: sample_004219/merged_surfaces.stl

sample_004219/merged_surfaces.stl:   0%|          | 0.00/31.3M [00:00<?, ?B/s]

[172/200] Downloading: sample_004237/merged_surfaces.stl

sample_004237/merged_surfaces.stl:   0%|          | 0.00/30.5M [00:00<?, ?B/s]

[173/200] Downloading: sample_004271/merged_surfaces.stl

sample_004271/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[174/200] Downloading: sample_004314/merged_surfaces.stl

sample_004314/merged_surfaces.stl:   0%|          | 0.00/26.8M [00:00<?, ?B/s]

[175/200] Downloading: sample_004376/merged_surfaces.stl

sample_004376/merged_surfaces.stl:   0%|          | 0.00/30.7M [00:00<?, ?B/s]

[176/200] Downloading: sample_004411/merged_surfaces.stl

sample_004411/merged_surfaces.stl:   0%|          | 0.00/26.1M [00:00<?, ?B/s]

[177/200] Downloading: sample_004520/merged_surfaces.stl

sample_004520/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[178/200] Downloading: sample_004543/merged_surfaces.stl

sample_004543/merged_surfaces.stl:   0%|          | 0.00/31.6M [00:00<?, ?B/s]

[179/200] Downloading: sample_004551/merged_surfaces.stl

sample_004551/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[180/200] Downloading: sample_004575/merged_surfaces.stl

sample_004575/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[181/200] Downloading: sample_004644/merged_surfaces.stl

sample_004644/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[182/200] Downloading: sample_004702/merged_surfaces.stl

sample_004702/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[183/200] Downloading: sample_004737/merged_surfaces.stl

sample_004737/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[184/200] Downloading: sample_004743/merged_surfaces.stl

sample_004743/merged_surfaces.stl:   0%|          | 0.00/26.3M [00:00<?, ?B/s]

[185/200] Downloading: sample_004759/merged_surfaces.stl

sample_004759/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[186/200] Downloading: sample_004808/merged_surfaces.stl

sample_004808/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[187/200] Downloading: sample_004855/merged_surfaces.stl

sample_004855/merged_surfaces.stl:   0%|          | 0.00/30.5M [00:00<?, ?B/s]

[188/200] Downloading: sample_004869/merged_surfaces.stl

sample_004869/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[189/200] Downloading: sample_004927/merged_surfaces.stl

sample_004927/merged_surfaces.stl:   0%|          | 0.00/26.9M [00:00<?, ?B/s]

[190/200] Downloading: sample_005054/merged_surfaces.stl

sample_005054/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[191/200] Downloading: sample_005073/merged_surfaces.stl

sample_005073/merged_surfaces.stl:   0%|          | 0.00/28.6M [00:00<?, ?B/s]

[192/200] Downloading: sample_005204/merged_surfaces.stl

sample_005204/merged_surfaces.stl:   0%|          | 0.00/29.3M [00:00<?, ?B/s]

[193/200] Downloading: sample_005241/merged_surfaces.stl

sample_005241/merged_surfaces.stl:   0%|          | 0.00/31.4M [00:00<?, ?B/s]

[194/200] Downloading: sample_005245/merged_surfaces.stl

sample_005245/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[195/200] Downloading: sample_005277/merged_surfaces.stl

sample_005277/merged_surfaces.stl:   0%|          | 0.00/31.0M [00:00<?, ?B/s]

[196/200] Downloading: sample_005327/merged_surfaces.stl

sample_005327/merged_surfaces.stl:   0%|          | 0.00/32.3M [00:00<?, ?B/s]

[197/200] Downloading: sample_005376/merged_surfaces.stl

sample_005376/merged_surfaces.stl:   0%|          | 0.00/26.3M [00:00<?, ?B/s]

[198/200] Downloading: sample_005414/merged_surfaces.stl

sample_005414/merged_surfaces.stl:   0%|          | 0.00/28.3M [00:00<?, ?B/s]

[199/200] Downloading: sample_005466/merged_surfaces.stl

sample_005466/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[200/200] Downloading: sample_005641/merged_surfaces.stl

sample_005641/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]