### Libs

In [1]:
import glob
import json
import os

import kennard_stone as ks
import polars as pl
from dotenv import load_dotenv
from huggingface_hub import HfApi, hf_hub_download, snapshot_download
from sklearn.preprocessing import StandardScaler

load_dotenv()

True

### Downloading Metadata: Existing files and Parameters

In [9]:
HF_TOKEN = os.getenv("HF_READ_TOKEN")
REPO_ID = "luminary-shift/Pump"
METADATA_DIR = "./pump_metadata"

In [10]:
api = HfApi(token=HF_TOKEN)

# Avoid re-downloading, load from local file
if not os.path.exists("shift_pump_files.txt"):
    # Download from HF
    all_files = api.list_repo_files(repo_id=REPO_ID, repo_type="dataset")
    with open("shift_pump_files.txt", "w") as f:
        f.writelines(f"{file}\n" for file in all_files)
else:
    with open("shift_pump_files.txt", "r") as f:
        all_files = f.read().splitlines()
params_json_files = [f for f in all_files if f.endswith("params.json")]

In [11]:
all_stl_files = [f for f in all_files if f.endswith("merged_surfaces.stl")]

In [12]:
existing_stls = glob.glob(os.path.join(METADATA_DIR, "**","*.stl"))
existing_stls = list(map(lambda str_path: os.path.join(*str_path.split('/')[2:]), existing_stls))
missing_stls = set(all_stl_files) - set(existing_stls)

In [13]:
len(missing_stls)

0

In [12]:
for f in params_json_files:
    hf_hub_download(repo_id=REPO_ID, token=HF_TOKEN,filename=f,local_dir=METADATA_DIR, repo_type="dataset")

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/968 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/969 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/973 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/972 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/971 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

params.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

ReadTimeout: The read operation timed out

### Read and Cast data

In [9]:
# Find all params.json files under pump_metadata
json_paths = sorted(glob.glob(os.path.join(METADATA_DIR, "sample_*", "params.json")))

# Load all json data into a list of dicts
records = []
for path in json_paths:
    with open(path, "r") as f:
        data = json.load(f)
        # Add the folder name as sample_id
        data["sample_id"] = os.path.basename(os.path.dirname(path))
        records.append(data)

# Create polars DataFrame
df = pl.DataFrame(records)

# Define column groupings for typing
float_cols = [
    "flow_rate",
    "head",
    "outer_diameter_factor",
    "outlet_width_factor",
    "shroud_diameter_factor",
    "volute_q_factor",
    "volute_r_factor",
    "teAngleDelta",
    "leAngleDelta",
    "compactness",
    "leWidthVar",
    "leRake",
    "teRake",
    "flow_rate_op_condition",
    "leShapevar",
    "shrAngleVar",
    "stream_velocity",
    "area_ref",
    "length_ref",
    "length_ref_pitch",
    "length_ref_roll",
    "length_ref_yaw",
    "moment_center_x",
    "moment_center_y",
    "moment_center_z",
    "R",
    "gamma",
    "cp",
    "air_density",
]

int_cols = [
    "rotational_speed",
    "fix_blade_number",
    "leAngleVar",
    "leShapeVar",
    "tipGap",
    "leEllipseFactor",
    "mach",
    "pressure",
    "temperature",
]

bool_cols = ["teTangential"]

# Apply casting expressions
cast_exprs = []

for col in float_cols:
    if col in df.columns:
        cast_exprs.append(pl.col(col).cast(pl.Float64))

for col in int_cols:
    if col in df.columns:
        cast_exprs.append(pl.col(col).cast(pl.Int64))

for col in bool_cols:
    if col in df.columns:
        # Handle string "true"/"false" safely
        if df[col].dtype == pl.String:
            cast_exprs.append(
                (pl.col(col).str.to_lowercase() == "true").cast(pl.Boolean)
            )
        else:
            cast_exprs.append(pl.col(col).cast(pl.Boolean))

df = df.with_columns(cast_exprs)

In [10]:
df.head()

shape: (0, 0)
┌┐
╞╡
└┘

In [11]:
df.describe()

TypeError: cannot describe a DataFrame that has no columns

### Applying Kennard-Stone to select most distinct geometries

In [11]:
# 1. Define the geometric columns to include in the shape analysis
active_geometric_cols = [
    "outer_diameter_factor",
    "outlet_width_factor",
    "shroud_diameter_factor",
    "teAngleDelta",
    "leAngleDelta",
    "compactness",
    "leWidthVar",
    "leRake",
    "teRake",
    "leShapevar",
]

# Ensure we only use columns that actually exist in the DataFrame
existing_geo_cols = [col for col in active_geometric_cols if col in df.columns]

# 2. Extract features, fill missing/null values, and cast booleans to floats
df_features = (
    df.select(existing_geo_cols)
    .with_columns(
        [
            # Cast boolean columns (like teTangential) to floats so they can be scaled
            pl.col(col).cast(pl.Float64)
            for col in existing_geo_cols
        ]
    )
    .fill_null(0.0)
)

X = df_features.to_numpy()

# 3. Scale features (essential so that features with larger ranges don't dominate the distance)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. Use the Kennard-Stone algorithm to select a diverse subset
# Set train_size to the number of shapes you want to download/encoder-fine-tune
num_to_select = 200

X_train, X_test, df_selected, df_remaining = ks.train_test_split(
    X_scaled, df, train_size=num_to_select
)

# 5. Output the selected sample folder names
selected_folders = df_selected["sample_id"].to_list()

print(f"Selected {len(selected_folders)} diverse shapes:")
print(selected_folders)

2026-07-10 11:12:26,705 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-07-10 11:12:27,377 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

Selected 200 diverse shapes:
['sample_002231', 'sample_002089', 'sample_003959', 'sample_001469', 'sample_000343', 'sample_001281', 'sample_000291', 'sample_001590', 'sample_001561', 'sample_001575', 'sample_001212', 'sample_001806', 'sample_004644', 'sample_004314', 'sample_004759', 'sample_001148', 'sample_003691', 'sample_000665', 'sample_003755', 'sample_001294', 'sample_001433', 'sample_000140', 'sample_000724', 'sample_001221', 'sample_003348', 'sample_002686', 'sample_000107', 'sample_003269', 'sample_002208', 'sample_003604', 'sample_000198', 'sample_001778', 'sample_002317', 'sample_002302', 'sample_001878', 'sample_004702', 'sample_000277', 'sample_002533', 'sample_000327', 'sample_001501', 'sample_000286', 'sample_001471', 'sample_000627', 'sample_000749', 'sample_000615', 'sample_002164', 'sample_001270', 'sample_001311', 'sample_002052', 'sample_000063', 'sample_002333', 'sample_000295', 'sample_004135', 'sample_000430', 'sample_001809', 'sample_000891', 'sample_000185', 'sample_001265', 'sample_001094', 'sample_004040', 'sample_000486', 'sample_001193', 'sample_003865', 'sample_001953', 'sample_001272', 'sample_001129', 'sample_003287', 'sample_002117', 'sample_002853', 'sample_003674', 'sample_001788', 'sample_003188', 'sample_001509', 'sample_001253', 'sample_000964', 'sample_000313', 'sample_002344', 'sample_004219', 'sample_000742', 'sample_003679', 'sample_002157', 'sample_004118', 'sample_002187', 'sample_001870', 'sample_000894', 'sample_000444', 'sample_004869', 'sample_000019', 'sample_001514', 'sample_004520', 'sample_002276', 'sample_000595', 'sample_000405', 'sample_000497', 'sample_004927', 'sample_002478', 'sample_002332', 'sample_001009', 'sample_000816', 'sample_003510', 'sample_001186', 'sample_000858', 'sample_001573', 'sample_000886', 'sample_000519', 'sample_004737', 'sample_003954', 'sample_003392', 'sample_000608', 'sample_001440', 'sample_004551', 'sample_003543', 'sample_002209', 'sample_001472', 'sample_000873', 'sample_001190', 'sample_002976', 'sample_002475', 'sample_002897', 'sample_003618', 'sample_000022', 'sample_000242', 'sample_005414', 'sample_000624', 'sample_001549', 'sample_004376', 'sample_005245', 'sample_001006', 'sample_000256', 'sample_001504', 'sample_005641', 'sample_000798', 'sample_001538', 'sample_000707', 'sample_000994', 'sample_000760', 'sample_002367', 'sample_002088', 'sample_000132', 'sample_002348', 'sample_002619', 'sample_003268', 'sample_004575', 'sample_005054', 'sample_003420', 'sample_001995', 'sample_005327', 'sample_000672', 'sample_005241', 'sample_001192', 'sample_004543', 'sample_001693', 'sample_003016', 'sample_001742', 'sample_002993', 'sample_004123', 'sample_002687', 'sample_002774', 'sample_003523', 'sample_000159', 'sample_002122', 'sample_003088', 'sample_004855', 'sample_003321', 'sample_004743', 'sample_005466', 'sample_001673', 'sample_001064', 'sample_001634', 'sample_001088', 'sample_005277', 'sample_002521', 'sample_001361', 'sample_001477', 'sample_002639', 'sample_004210', 'sample_002372', 'sample_001343', 'sample_002441', 'sample_002964', 'sample_005376', 'sample_003811', 'sample_005073', 'sample_002574', 'sample_003328', 'sample_000333', 'sample_000541', 'sample_000484', 'sample_000908', 'sample_004808', 'sample_005204', 'sample_004411', 'sample_000153', 'sample_002042', 'sample_003200', 'sample_001718', 'sample_002392', 'sample_004271', 'sample_000422', 'sample_004237']

In [13]:
df_filtered = df_selected.filter(pl.col("sample_id").is_in(selected_folders))
df_filtered.select(active_geometric_cols).describe()

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ outer_dia ┆ outlet_wi ┆ shroud_di ┆ … ┆ leWidthVa ┆ leRake   ┆ teRake    ┆ leShapeva │
│ ---       ┆ meter_fac ┆ dth_facto ┆ ameter_fa ┆   ┆ r         ┆ ---      ┆ ---       ┆ r         │
│ str       ┆ tor       ┆ r         ┆ ctor      ┆   ┆ ---       ┆ f64      ┆ f64       ┆ ---       │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆          ┆           ┆ f64       │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 200.0     ┆ 200.0     ┆ 200.0     ┆ … ┆ 200.0     ┆ 200.0    ┆ 200.0     ┆ 200.0     │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ 0.0       │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ 0.975348  ┆ 0.998496  ┆ 1.0763075 ┆ … ┆ 1.000147  ┆ 9.790015 ┆ 10.058493 ┆ 0.144926  │
│ std       ┆ 0.017357  ┆ 0.068568  ┆ 0.050778  ┆ … ┆ 0.068701  ┆ 6.686674 ┆ 6.655577  ┆ 0.103324  │
│ min       ┆ 0.9501    ┆ 0.9002    ┆ 1.0002    ┆ … ┆ 0.9       ┆ 0.0749   ┆ 0.0085    ┆ 0.0002    │
│ 25%       ┆ 0.9584    ┆ 0.9281    ┆ 1.0273    ┆ … ┆ 0.9315    ┆ 3.0698   ┆ 3.3927    ┆ 0.0442    │
│ 50%       ┆ 0.9745    ┆ 1.0025    ┆ 1.0772    ┆ … ┆ 1.0008    ┆ 10.7351  ┆ 10.4506   ┆ 0.1423    │
│ 75%       ┆ 0.9938    ┆ 1.065     ┆ 1.1284    ┆ … ┆ 1.07      ┆ 16.1506  ┆ 16.2815   ┆ 0.2448    │
│ max       ┆ 0.9998    ┆ 1.0994    ┆ 1.15      ┆ … ┆ 1.0991    ┆ 19.9997  ┆ 19.9917   ┆ 0.2997    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

### Download ONLY selected pumps from KS

In [14]:
all_files
pump_stl_selected_files = [
    f
    for f in all_files
    if (f.endswith(".stl") and (f.split("/")[0] in selected_folders))
]

In [15]:
pump_stl_selected_files[:5]

['sample_000019/merged_surfaces.stl',
 'sample_000022/merged_surfaces.stl',
 'sample_000063/merged_surfaces.stl',
 'sample_000107/merged_surfaces.stl',
 'sample_000132/merged_surfaces.stl']

In [ ]:
snapshot_download(
    repo_id=REPO_ID,
    token=HF_TOKEN,
    repo_type="dataset",
    local_dir=METADATA_DIR,
    allow_patterns=pump_stl_selected_files,  # Ou ["*.stl"] se for a pasta inteira
    max_workers=4,  # Ajuste entre 4 e 8 para acelerar o download
)

[1/5646] Downloading: sample_000001/merged_surfaces.stl

sample_000001/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[2/5646] Downloading: sample_000002/merged_surfaces.stl

sample_000002/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[3/5646] Downloading: sample_000003/merged_surfaces.stl

sample_000003/merged_surfaces.stl:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

[4/5646] Downloading: sample_000004/merged_surfaces.stl

sample_000004/merged_surfaces.stl:   0%|          | 0.00/31.2M [00:00<?, ?B/s]

[5/5646] Downloading: sample_000005/merged_surfaces.stl

sample_000005/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[6/5646] Downloading: sample_000006/merged_surfaces.stl

sample_000006/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[7/5646] Downloading: sample_000007/merged_surfaces.stl

sample_000007/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[8/5646] Downloading: sample_000008/merged_surfaces.stl

sample_000008/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[9/5646] Downloading: sample_000009/merged_surfaces.stl

sample_000009/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[10/5646] Downloading: sample_000010/merged_surfaces.stl

sample_000010/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[11/5646] Downloading: sample_000011/merged_surfaces.stl

sample_000011/merged_surfaces.stl:   0%|          | 0.00/26.5M [00:00<?, ?B/s]

[12/5646] Downloading: sample_000012/merged_surfaces.stl

sample_000012/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[13/5646] Downloading: sample_000013/merged_surfaces.stl

sample_000013/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[14/5646] Downloading: sample_000014/merged_surfaces.stl

sample_000014/merged_surfaces.stl:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

[15/5646] Downloading: sample_000015/merged_surfaces.stl

sample_000015/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[16/5646] Downloading: sample_000016/merged_surfaces.stl

sample_000016/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[17/5646] Downloading: sample_000017/merged_surfaces.stl

sample_000017/merged_surfaces.stl:   0%|          | 0.00/26.3M [00:00<?, ?B/s]

[18/5646] Downloading: sample_000018/merged_surfaces.stl

sample_000018/merged_surfaces.stl:   0%|          | 0.00/30.6M [00:00<?, ?B/s]

[19/5646] Downloading: sample_000019/merged_surfaces.stl

sample_000019/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[20/5646] Downloading: sample_000020/merged_surfaces.stl

sample_000020/merged_surfaces.stl:   0%|          | 0.00/30.5M [00:00<?, ?B/s]

[21/5646] Downloading: sample_000021/merged_surfaces.stl

sample_000021/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[22/5646] Downloading: sample_000022/merged_surfaces.stl

sample_000022/merged_surfaces.stl:   0%|          | 0.00/29.3M [00:00<?, ?B/s]

[23/5646] Downloading: sample_000023/merged_surfaces.stl

sample_000023/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[24/5646] Downloading: sample_000024/merged_surfaces.stl

sample_000024/merged_surfaces.stl:   0%|          | 0.00/26.1M [00:00<?, ?B/s]

[25/5646] Downloading: sample_000025/merged_surfaces.stl

sample_000025/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[26/5646] Downloading: sample_000026/merged_surfaces.stl

sample_000026/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[27/5646] Downloading: sample_000027/merged_surfaces.stl

sample_000027/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[28/5646] Downloading: sample_000028/merged_surfaces.stl

sample_000028/merged_surfaces.stl:   0%|          | 0.00/31.0M [00:00<?, ?B/s]

[29/5646] Downloading: sample_000029/merged_surfaces.stl

sample_000029/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[30/5646] Downloading: sample_000030/merged_surfaces.stl

sample_000030/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[31/5646] Downloading: sample_000031/merged_surfaces.stl

sample_000031/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[32/5646] Downloading: sample_000032/merged_surfaces.stl

sample_000032/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[33/5646] Downloading: sample_000033/merged_surfaces.stl

sample_000033/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[34/5646] Downloading: sample_000034/merged_surfaces.stl

sample_000034/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[35/5646] Downloading: sample_000035/merged_surfaces.stl

sample_000035/merged_surfaces.stl:   0%|          | 0.00/27.3M [00:00<?, ?B/s]

[36/5646] Downloading: sample_000036/merged_surfaces.stl

sample_000036/merged_surfaces.stl:   0%|          | 0.00/25.9M [00:00<?, ?B/s]

[37/5646] Downloading: sample_000037/merged_surfaces.stl

sample_000037/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[38/5646] Downloading: sample_000038/merged_surfaces.stl

sample_000038/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

### Downlaod ALL MISSING PUMPS! TOTAL OF 160 GB!!

In [8]:

# Baixa apenas os arquivos especificados em paralelo
snapshot_download(
    repo_id=REPO_ID,
    token=HF_TOKEN,
    repo_type="dataset",
    local_dir=METADATA_DIR,
    allow_patterns=missing_stls,  # Ou ["*.stl"] se for a pasta inteira
    max_workers=4,  # Ajuste entre 4 e 8 para acelerar o download
)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 1925 files:   0%|          | 0/1925 [00:00<?, ?it/s]

'/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/pump_metadata'

In [ ]:
# Iterate and download each selected STL file

for idx, f in enumerate(all_stl_files[974:], 975):
    print(f"[{idx}/{len(all_stl_files)}] Downloading: {f}")
#for idx, f in enumerate(pump_stl_selected_files, 1):
#    print(f"[{idx}/{len(pump_stl_selected_files)}] Downloading: {f}")
    if (idx%150 == 0):
        sleep(30)
    try:
        hf_hub_download(
            repo_id=REPO_ID,
            token=HF_TOKEN,
            filename=f,
            local_dir=METADATA_DIR,
            repo_type="dataset",
        )
    except Exception as e:
        print(f"Failed to download {f}: {e}")

[975/5646] Downloading: sample_000975/merged_surfaces.stl

sample_000975/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[976/5646] Downloading: sample_000976/merged_surfaces.stl

sample_000976/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[977/5646] Downloading: sample_000977/merged_surfaces.stl

sample_000977/merged_surfaces.stl:   0%|          | 0.00/31.1M [00:00<?, ?B/s]

[978/5646] Downloading: sample_000978/merged_surfaces.stl

sample_000978/merged_surfaces.stl:   0%|          | 0.00/30.7M [00:00<?, ?B/s]

[979/5646] Downloading: sample_000979/merged_surfaces.stl

sample_000979/merged_surfaces.stl:   0%|          | 0.00/27.1M [00:00<?, ?B/s]

[980/5646] Downloading: sample_000980/merged_surfaces.stl

sample_000980/merged_surfaces.stl:   0%|          | 0.00/30.5M [00:00<?, ?B/s]

[981/5646] Downloading: sample_000981/merged_surfaces.stl

sample_000981/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[982/5646] Downloading: sample_000982/merged_surfaces.stl

sample_000982/merged_surfaces.stl:   0%|          | 0.00/26.9M [00:00<?, ?B/s]

[983/5646] Downloading: sample_000983/merged_surfaces.stl

sample_000983/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[984/5646] Downloading: sample_000984/merged_surfaces.stl

sample_000984/merged_surfaces.stl:   0%|          | 0.00/28.6M [00:00<?, ?B/s]

[985/5646] Downloading: sample_000985/merged_surfaces.stl

sample_000985/merged_surfaces.stl:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

[986/5646] Downloading: sample_000986/merged_surfaces.stl

sample_000986/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[987/5646] Downloading: sample_000987/merged_surfaces.stl

sample_000987/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[988/5646] Downloading: sample_000988/merged_surfaces.stl

sample_000988/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[989/5646] Downloading: sample_000989/merged_surfaces.stl

sample_000989/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[990/5646] Downloading: sample_000990/merged_surfaces.stl

sample_000990/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[991/5646] Downloading: sample_000991/merged_surfaces.stl

sample_000991/merged_surfaces.stl:   0%|          | 0.00/27.5M [00:00<?, ?B/s]

[992/5646] Downloading: sample_000992/merged_surfaces.stl

sample_000992/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[993/5646] Downloading: sample_000993/merged_surfaces.stl

sample_000993/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[994/5646] Downloading: sample_000994/merged_surfaces.stl

sample_000994/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[995/5646] Downloading: sample_000995/merged_surfaces.stl

sample_000995/merged_surfaces.stl:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

[996/5646] Downloading: sample_000996/merged_surfaces.stl

sample_000996/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[997/5646] Downloading: sample_000997/merged_surfaces.stl

sample_000997/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[998/5646] Downloading: sample_000998/merged_surfaces.stl

sample_000998/merged_surfaces.stl:   0%|          | 0.00/27.2M [00:00<?, ?B/s]

[999/5646] Downloading: sample_000999/merged_surfaces.stl

sample_000999/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[1000/5646] Downloading: sample_001000/merged_surfaces.stl

sample_001000/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[1001/5646] Downloading: sample_001001/merged_surfaces.stl

sample_001001/merged_surfaces.stl:   0%|          | 0.00/30.2M [00:00<?, ?B/s]

[1002/5646] Downloading: sample_001002/merged_surfaces.stl

sample_001002/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[1003/5646] Downloading: sample_001003/merged_surfaces.stl

sample_001003/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[1004/5646] Downloading: sample_001004/merged_surfaces.stl

sample_001004/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[1005/5646] Downloading: sample_001005/merged_surfaces.stl

sample_001005/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[1006/5646] Downloading: sample_001006/merged_surfaces.stl

sample_001006/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[1007/5646] Downloading: sample_001007/merged_surfaces.stl

sample_001007/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[1008/5646] Downloading: sample_001008/merged_surfaces.stl

sample_001008/merged_surfaces.stl:   0%|          | 0.00/32.0M [00:00<?, ?B/s]

[1009/5646] Downloading: sample_001009/merged_surfaces.stl

sample_001009/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[1010/5646] Downloading: sample_001010/merged_surfaces.stl

sample_001010/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[1011/5646] Downloading: sample_001011/merged_surfaces.stl

sample_001011/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[1012/5646] Downloading: sample_001012/merged_surfaces.stl

sample_001012/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[1013/5646] Downloading: sample_001013/merged_surfaces.stl

sample_001013/merged_surfaces.stl:   0%|          | 0.00/26.5M [00:00<?, ?B/s]

[1014/5646] Downloading: sample_001014/merged_surfaces.stl

sample_001014/merged_surfaces.stl:   0%|          | 0.00/27.3M [00:00<?, ?B/s]

[1015/5646] Downloading: sample_001015/merged_surfaces.stl

sample_001015/merged_surfaces.stl:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

[1016/5646] Downloading: sample_001016/merged_surfaces.stl

sample_001016/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[1017/5646] Downloading: sample_001017/merged_surfaces.stl

sample_001017/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[1018/5646] Downloading: sample_001018/merged_surfaces.stl

sample_001018/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[1019/5646] Downloading: sample_001019/merged_surfaces.stl

sample_001019/merged_surfaces.stl:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

[1020/5646] Downloading: sample_001020/merged_surfaces.stl

sample_001020/merged_surfaces.stl:   0%|          | 0.00/27.4M [00:00<?, ?B/s]

[1021/5646] Downloading: sample_001021/merged_surfaces.stl

sample_001021/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[1022/5646] Downloading: sample_001022/merged_surfaces.stl

sample_001022/merged_surfaces.stl:   0%|          | 0.00/24.7M [00:00<?, ?B/s]

[1023/5646] Downloading: sample_001023/merged_surfaces.stl

sample_001023/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[1024/5646] Downloading: sample_001024/merged_surfaces.stl

sample_001024/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[1025/5646] Downloading: sample_001025/merged_surfaces.stl

sample_001025/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[1026/5646] Downloading: sample_001026/merged_surfaces.stl

sample_001026/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[1027/5646] Downloading: sample_001027/merged_surfaces.stl

sample_001027/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[1028/5646] Downloading: sample_001028/merged_surfaces.stl

sample_001028/merged_surfaces.stl:   0%|          | 0.00/27.8M [00:00<?, ?B/s]

[1029/5646] Downloading: sample_001029/merged_surfaces.stl

sample_001029/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[1030/5646] Downloading: sample_001030/merged_surfaces.stl

sample_001030/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[1031/5646] Downloading: sample_001031/merged_surfaces.stl

sample_001031/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[1032/5646] Downloading: sample_001032/merged_surfaces.stl

sample_001032/merged_surfaces.stl:   0%|          | 0.00/31.7M [00:00<?, ?B/s]

[1033/5646] Downloading: sample_001033/merged_surfaces.stl

sample_001033/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[1034/5646] Downloading: sample_001034/merged_surfaces.stl

sample_001034/merged_surfaces.stl:   0%|          | 0.00/27.2M [00:00<?, ?B/s]

[1035/5646] Downloading: sample_001035/merged_surfaces.stl

sample_001035/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[1036/5646] Downloading: sample_001036/merged_surfaces.stl

sample_001036/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[1037/5646] Downloading: sample_001037/merged_surfaces.stl

sample_001037/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[1038/5646] Downloading: sample_001038/merged_surfaces.stl

sample_001038/merged_surfaces.stl:   0%|          | 0.00/26.8M [00:00<?, ?B/s]

[1039/5646] Downloading: sample_001039/merged_surfaces.stl

sample_001039/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[1040/5646] Downloading: sample_001040/merged_surfaces.stl

sample_001040/merged_surfaces.stl:   0%|          | 0.00/30.4M [00:00<?, ?B/s]

[1041/5646] Downloading: sample_001041/merged_surfaces.stl

sample_001041/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[1042/5646] Downloading: sample_001042/merged_surfaces.stl

sample_001042/merged_surfaces.stl:   0%|          | 0.00/30.3M [00:00<?, ?B/s]

[1043/5646] Downloading: sample_001043/merged_surfaces.stl

sample_001043/merged_surfaces.stl:   0%|          | 0.00/26.3M [00:00<?, ?B/s]

[1044/5646] Downloading: sample_001044/merged_surfaces.stl

sample_001044/merged_surfaces.stl:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

[1045/5646] Downloading: sample_001045/merged_surfaces.stl

sample_001045/merged_surfaces.stl:   0%|          | 0.00/25.1M [00:00<?, ?B/s]

[1046/5646] Downloading: sample_001046/merged_surfaces.stl

sample_001046/merged_surfaces.stl:   0%|          | 0.00/30.3M [00:00<?, ?B/s]

[1047/5646] Downloading: sample_001047/merged_surfaces.stl

sample_001047/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[1048/5646] Downloading: sample_001048/merged_surfaces.stl

sample_001048/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[1049/5646] Downloading: sample_001049/merged_surfaces.stl

sample_001049/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[1050/5646] Downloading: sample_001050/merged_surfaces.stl

sample_001050/merged_surfaces.stl:   0%|          | 0.00/26.4M [00:00<?, ?B/s]

[1051/5646] Downloading: sample_001051/merged_surfaces.stl

sample_001051/merged_surfaces.stl:   0%|          | 0.00/27.5M [00:00<?, ?B/s]

[1052/5646] Downloading: sample_001052/merged_surfaces.stl

sample_001052/merged_surfaces.stl:   0%|          | 0.00/30.6M [00:00<?, ?B/s]

[1053/5646] Downloading: sample_001053/merged_surfaces.stl

sample_001053/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[1054/5646] Downloading: sample_001054/merged_surfaces.stl

sample_001054/merged_surfaces.stl:   0%|          | 0.00/32.1M [00:00<?, ?B/s]

[1055/5646] Downloading: sample_001055/merged_surfaces.stl

sample_001055/merged_surfaces.stl:   0%|          | 0.00/28.3M [00:00<?, ?B/s]

[1056/5646] Downloading: sample_001056/merged_surfaces.stl

sample_001056/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[1057/5646] Downloading: sample_001057/merged_surfaces.stl

sample_001057/merged_surfaces.stl:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

[1058/5646] Downloading: sample_001058/merged_surfaces.stl

sample_001058/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[1059/5646] Downloading: sample_001059/merged_surfaces.stl

sample_001059/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[1060/5646] Downloading: sample_001060/merged_surfaces.stl

sample_001060/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[1061/5646] Downloading: sample_001061/merged_surfaces.stl

sample_001061/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[1062/5646] Downloading: sample_001062/merged_surfaces.stl

sample_001062/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[1063/5646] Downloading: sample_001063/merged_surfaces.stl

sample_001063/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[1064/5646] Downloading: sample_001064/merged_surfaces.stl

sample_001064/merged_surfaces.stl:   0%|          | 0.00/31.4M [00:00<?, ?B/s]

[1065/5646] Downloading: sample_001065/merged_surfaces.stl

sample_001065/merged_surfaces.stl:   0%|          | 0.00/29.7M [00:00<?, ?B/s]

[1066/5646] Downloading: sample_001066/merged_surfaces.stl

sample_001066/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[1067/5646] Downloading: sample_001067/merged_surfaces.stl

sample_001067/merged_surfaces.stl:   0%|          | 0.00/25.9M [00:00<?, ?B/s]

[1068/5646] Downloading: sample_001068/merged_surfaces.stl

sample_001068/merged_surfaces.stl:   0%|          | 0.00/27.1M [00:00<?, ?B/s]

[1069/5646] Downloading: sample_001069/merged_surfaces.stl

sample_001069/merged_surfaces.stl:   0%|          | 0.00/30.8M [00:00<?, ?B/s]

[1070/5646] Downloading: sample_001070/merged_surfaces.stl

sample_001070/merged_surfaces.stl:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

[1071/5646] Downloading: sample_001071/merged_surfaces.stl

sample_001071/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[1072/5646] Downloading: sample_001072/merged_surfaces.stl

sample_001072/merged_surfaces.stl:   0%|          | 0.00/27.2M [00:00<?, ?B/s]

[1073/5646] Downloading: sample_001073/merged_surfaces.stl

sample_001073/merged_surfaces.stl:   0%|          | 0.00/29.3M [00:00<?, ?B/s]

[1074/5646] Downloading: sample_001074/merged_surfaces.stl

sample_001074/merged_surfaces.stl:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

[1075/5646] Downloading: sample_001075/merged_surfaces.stl

sample_001075/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[1076/5646] Downloading: sample_001076/merged_surfaces.stl

sample_001076/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[1077/5646] Downloading: sample_001077/merged_surfaces.stl

sample_001077/merged_surfaces.stl:   0%|          | 0.00/27.2M [00:00<?, ?B/s]

[1078/5646] Downloading: sample_001078/merged_surfaces.stl

sample_001078/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[1079/5646] Downloading: sample_001079/merged_surfaces.stl

sample_001079/merged_surfaces.stl:   0%|          | 0.00/28.2M [00:00<?, ?B/s]

[1080/5646] Downloading: sample_001080/merged_surfaces.stl

sample_001080/merged_surfaces.stl:   0%|          | 0.00/27.3M [00:00<?, ?B/s]

[1081/5646] Downloading: sample_001081/merged_surfaces.stl

sample_001081/merged_surfaces.stl:   0%|          | 0.00/30.7M [00:00<?, ?B/s]

[1082/5646] Downloading: sample_001082/merged_surfaces.stl

sample_001082/merged_surfaces.stl:   0%|          | 0.00/30.6M [00:00<?, ?B/s]

[1083/5646] Downloading: sample_001083/merged_surfaces.stl

sample_001083/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[1084/5646] Downloading: sample_001084/merged_surfaces.stl

sample_001084/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[1085/5646] Downloading: sample_001085/merged_surfaces.stl

sample_001085/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[1086/5646] Downloading: sample_001086/merged_surfaces.stl

sample_001086/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[1087/5646] Downloading: sample_001087/merged_surfaces.stl

sample_001087/merged_surfaces.stl:   0%|          | 0.00/25.5M [00:00<?, ?B/s]

[1088/5646] Downloading: sample_001088/merged_surfaces.stl

sample_001088/merged_surfaces.stl:   0%|          | 0.00/26.7M [00:00<?, ?B/s]

[1089/5646] Downloading: sample_001089/merged_surfaces.stl

sample_001089/merged_surfaces.stl:   0%|          | 0.00/28.1M [00:00<?, ?B/s]

[1090/5646] Downloading: sample_001090/merged_surfaces.stl

sample_001090/merged_surfaces.stl:   0%|          | 0.00/25.9M [00:00<?, ?B/s]

[1091/5646] Downloading: sample_001091/merged_surfaces.stl

sample_001091/merged_surfaces.stl:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

[1092/5646] Downloading: sample_001092/merged_surfaces.stl

sample_001092/merged_surfaces.stl:   0%|          | 0.00/32.2M [00:00<?, ?B/s]

[1093/5646] Downloading: sample_001093/merged_surfaces.stl

sample_001093/merged_surfaces.stl:   0%|          | 0.00/29.4M [00:00<?, ?B/s]

[1094/5646] Downloading: sample_001094/merged_surfaces.stl

sample_001094/merged_surfaces.stl:   0%|          | 0.00/25.3M [00:00<?, ?B/s]

[1095/5646] Downloading: sample_001095/merged_surfaces.stl

sample_001095/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[1096/5646] Downloading: sample_001096/merged_surfaces.stl

sample_001096/merged_surfaces.stl:   0%|          | 0.00/28.7M [00:00<?, ?B/s]

[1097/5646] Downloading: sample_001097/merged_surfaces.stl

sample_001097/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[1098/5646] Downloading: sample_001098/merged_surfaces.stl

sample_001098/merged_surfaces.stl:   0%|          | 0.00/26.5M [00:00<?, ?B/s]

[1099/5646] Downloading: sample_001099/merged_surfaces.stl

sample_001099/merged_surfaces.stl:   0%|          | 0.00/26.4M [00:00<?, ?B/s]

[1100/5646] Downloading: sample_001100/merged_surfaces.stl

sample_001100/merged_surfaces.stl:   0%|          | 0.00/26.6M [00:00<?, ?B/s]

[1101/5646] Downloading: sample_001101/merged_surfaces.stl

sample_001101/merged_surfaces.stl:   0%|          | 0.00/28.8M [00:00<?, ?B/s]

[1102/5646] Downloading: sample_001102/merged_surfaces.stl

sample_001102/merged_surfaces.stl:   0%|          | 0.00/26.8M [00:00<?, ?B/s]

[1103/5646] Downloading: sample_001103/merged_surfaces.stl

sample_001103/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[1104/5646] Downloading: sample_001104/merged_surfaces.stl

sample_001104/merged_surfaces.stl:   0%|          | 0.00/28.5M [00:00<?, ?B/s]

[1105/5646] Downloading: sample_001105/merged_surfaces.stl

sample_001105/merged_surfaces.stl:   0%|          | 0.00/26.9M [00:00<?, ?B/s]

[1106/5646] Downloading: sample_001106/merged_surfaces.stl

sample_001106/merged_surfaces.stl:   0%|          | 0.00/31.5M [00:00<?, ?B/s]

[1107/5646] Downloading: sample_001107/merged_surfaces.stl

sample_001107/merged_surfaces.stl:   0%|          | 0.00/30.2M [00:00<?, ?B/s]

[1108/5646] Downloading: sample_001108/merged_surfaces.stl

sample_001108/merged_surfaces.stl:   0%|          | 0.00/31.3M [00:00<?, ?B/s]

[1109/5646] Downloading: sample_001109/merged_surfaces.stl

sample_001109/merged_surfaces.stl:   0%|          | 0.00/26.0M [00:00<?, ?B/s]

[1110/5646] Downloading: sample_001110/merged_surfaces.stl

sample_001110/merged_surfaces.stl:   0%|          | 0.00/29.6M [00:00<?, ?B/s]

[1111/5646] Downloading: sample_001111/merged_surfaces.stl

sample_001111/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[1112/5646] Downloading: sample_001112/merged_surfaces.stl

sample_001112/merged_surfaces.stl:   0%|          | 0.00/28.6M [00:00<?, ?B/s]

[1113/5646] Downloading: sample_001113/merged_surfaces.stl

sample_001113/merged_surfaces.stl:   0%|          | 0.00/28.4M [00:00<?, ?B/s]

[1114/5646] Downloading: sample_001114/merged_surfaces.stl

sample_001114/merged_surfaces.stl:   0%|          | 0.00/26.4M [00:00<?, ?B/s]

[1115/5646] Downloading: sample_001115/merged_surfaces.stl

sample_001115/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[1116/5646] Downloading: sample_001116/merged_surfaces.stl

sample_001116/merged_surfaces.stl:   0%|          | 0.00/27.7M [00:00<?, ?B/s]

[1117/5646] Downloading: sample_001117/merged_surfaces.stl

sample_001117/merged_surfaces.stl:   0%|          | 0.00/30.7M [00:00<?, ?B/s]

[1118/5646] Downloading: sample_001118/merged_surfaces.stl

sample_001118/merged_surfaces.stl:   0%|          | 0.00/31.2M [00:00<?, ?B/s]

[1119/5646] Downloading: sample_001119/merged_surfaces.stl

sample_001119/merged_surfaces.stl:   0%|          | 0.00/29.5M [00:00<?, ?B/s]

[1120/5646] Downloading: sample_001120/merged_surfaces.stl

sample_001120/merged_surfaces.stl:   0%|          | 0.00/28.0M [00:00<?, ?B/s]

[1121/5646] Downloading: sample_001121/merged_surfaces.stl

sample_001121/merged_surfaces.stl:   0%|          | 0.00/29.1M [00:00<?, ?B/s]

[1122/5646] Downloading: sample_001122/merged_surfaces.stl

sample_001122/merged_surfaces.stl:   0%|          | 0.00/29.8M [00:00<?, ?B/s]

[1123/5646] Downloading: sample_001123/merged_surfaces.stl

sample_001123/merged_surfaces.stl:   0%|          | 0.00/29.3M [00:00<?, ?B/s]

[1124/5646] Downloading: sample_001124/merged_surfaces.stl

sample_001124/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

[1125/5646] Downloading: sample_001125/merged_surfaces.stl

sample_001125/merged_surfaces.stl:   0%|          | 0.00/30.5M [00:00<?, ?B/s]

[1126/5646] Downloading: sample_001126/merged_surfaces.stl

sample_001126/merged_surfaces.stl:   0%|          | 0.00/27.5M [00:00<?, ?B/s]

[1127/5646] Downloading: sample_001127/merged_surfaces.stl

sample_001127/merged_surfaces.stl:   0%|          | 0.00/27.0M [00:00<?, ?B/s]

[1128/5646] Downloading: sample_001128/merged_surfaces.stl

sample_001128/merged_surfaces.stl:   0%|          | 0.00/27.6M [00:00<?, ?B/s]

[1129/5646] Downloading: sample_001129/merged_surfaces.stl

sample_001129/merged_surfaces.stl:   0%|          | 0.00/30.9M [00:00<?, ?B/s]

[1130/5646] Downloading: sample_001130/merged_surfaces.stl

sample_001130/merged_surfaces.stl:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

[1131/5646] Downloading: sample_001131/merged_surfaces.stl

sample_001131/merged_surfaces.stl:   0%|          | 0.00/29.2M [00:00<?, ?B/s]

[1132/5646] Downloading: sample_001132/merged_surfaces.stl

sample_001132/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[1133/5646] Downloading: sample_001133/merged_surfaces.stl

sample_001133/merged_surfaces.stl:   0%|          | 0.00/29.9M [00:00<?, ?B/s]

[1134/5646] Downloading: sample_001134/merged_surfaces.stl

sample_001134/merged_surfaces.stl:   0%|          | 0.00/30.1M [00:00<?, ?B/s]

[1135/5646] Downloading: sample_001135/merged_surfaces.stl

sample_001135/merged_surfaces.stl:   0%|          | 0.00/29.0M [00:00<?, ?B/s]

Error in sys.excepthook:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 217, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 2112, in excepthook
    self.showtraceback((etype, value, tb), tb_offset=0)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 2234, in showtraceback
    self._showtraceback(etype, value, stb)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 669, in _showtraceback
    sys.stdout.flush()
    ~~~~~~~~~~~~~~~~^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 685, in flush
    self.pub_thread.schedule(self._flush)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 342, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 221, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/zmq/sugar/context.py", line 352, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py", line 162, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "zmq/backend/cython/_zmq.py", line 740, in zmq.backend.cython._zmq.Socket.__init__
    raise ZMQError()

zmq.error.ZMQError: Too many open files

Original exception was:
Traceback (most recent call last):
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 217, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/tqdm/notebook.py", line 262, in update
    return super().update(n=n)
           ~~~~~~~~~~~~~~^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/tqdm/std.py", line 1248, in update
    self.refresh(lock_args=self.lock_args)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/tqdm/std.py", line 1353, in refresh
    self.display()
    ~~~~~~~~~~~~^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/tqdm/notebook.py", line 173, in display
    rtext.value = right
    ^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/traitlets/traitlets.py", line 735, in __set__
    self.set(obj, value)
    ~~~~~~~~^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/traitlets/traitlets.py", line 725, in set
    obj._notify_trait(self.name, old_value, new_value)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/traitlets/traitlets.py", line 1521, in _notify_trait
    self.notify_change(
    ~~~~~~~~~~~~~~~~~~^
        Bunch(
        ^^^^^^
    ...<5 lines>...
        )
        ^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipywidgets/widgets/widget.py", line 700, in notify_change
    self.send_state(key=name)
    ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipywidgets/widgets/widget.py", line 586, in send_state
    self._send(msg, buffers=buffers)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipywidgets/widgets/widget.py", line 825, in _send
    self.comm.send(data=msg, buffers=buffers)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/comm/base_comm.py", line 144, in send
    self.publish_msg(
    ~~~~~~~~~~~~~~~~^
        "comm_msg",
        ^^^^^^^^^^^
    ...<2 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/comm/comm.py", line 37, in publish_msg
    self.kernel.session.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        self.kernel.iopub_socket,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/jupyter_client/session.py", line 867, in send
    stream.send_multipart(to_send, copy=copy)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 433, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 351, in send_multipart
    self.schedule(lambda: self._really_send(*args, **kwargs))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 342, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 221, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/zmq/sugar/context.py", line 352, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py", line 162, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "zmq/backend/cython/_zmq.py", line 740, in zmq.backend.cython._zmq.Socket.__init__
    raise ZMQError()

zmq.error.ZMQError: Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 217, in _event_pipe
    event_pipe = self._local.event_pipe
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_thread._local' object has no attribute 'event_pipe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/huggingface_hub/file_download.py", line 564, in _on_progress
    progress.update(max(0, current - _prev))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/tqdm/notebook.py", line 267, in update
    self.disp(bar_style='danger')
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/tqdm/notebook.py", line 180, in display
    pbar.bar_style = bar_style
    ^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/traitlets/traitlets.py", line 735, in __set__
    self.set(obj, value)
    ~~~~~~~~^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/traitlets/traitlets.py", line 725, in set
    obj._notify_trait(self.name, old_value, new_value)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/traitlets/traitlets.py", line 1521, in _notify_trait
    self.notify_change(
    ~~~~~~~~~~~~~~~~~~^
        Bunch(
        ^^^^^^
    ...<5 lines>...
        )
        ^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipywidgets/widgets/widget.py", line 700, in notify_change
    self.send_state(key=name)
    ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipywidgets/widgets/widget.py", line 586, in send_state
    self._send(msg, buffers=buffers)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipywidgets/widgets/widget.py", line 825, in _send
    self.comm.send(data=msg, buffers=buffers)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/comm/base_comm.py", line 144, in send
    self.publish_msg(
    ~~~~~~~~~~~~~~~~^
        "comm_msg",
        ^^^^^^^^^^^
    ...<2 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/comm/comm.py", line 37, in publish_msg
    self.kernel.session.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        self.kernel.iopub_socket,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        buffers=buffers,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/jupyter_client/session.py", line 867, in send
    stream.send_multipart(to_send, copy=copy)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 433, in send_multipart
    return self.io_thread.send_multipart(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 351, in send_multipart
    self.schedule(lambda: self._really_send(*args, **kwargs))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 342, in schedule
    self._event_pipe.send(b"")
    ^^^^^^^^^^^^^^^^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/ipykernel/iostream.py", line 221, in _event_pipe
    event_pipe = ctx.socket(zmq.PUSH)
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/zmq/sugar/context.py", line 352, in socket
    socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self, socket_type, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/vpspepe/Documents/TUD/HiWi/Ecotwin/POC_Tests/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py", line 162, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        ctx_or_socket,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        copy_threshold=copy_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "zmq/backend/cython/_zmq.py", line 740, in zmq.backend.cython._zmq.Socket.__init__
    raise ZMQError()

zmq.error.ZMQError: Too many open files

KeyboardInterrupt: